package nginx_log

import "github.com/uozi-tech/cosy"

var (
	e                                      = cosy.NewErrorScope("nginx_log")
	ErrLogPathIsNotUnderTheLogDirWhiteList = e.New(50001, "the log path is not under the paths in settings.NginxSettings.LogDirWhiteList")
	ErrServerIdxOutOfRange                 = e.New(50002, "serverIdx out of range")
	ErrDirectiveIdxOutOfRange              = e.New(50003, "directiveIdx out of range")
	ErrLogDirective                        = e.New(50004, "directive.Params neither access_log nor error_log")
	ErrDirectiveParamsIsEmpty              = e.New(50005, "directive params is empty")
	ErrErrorLogPathIsEmpty                 = e.New(50006, "settings.NginxLogSettings.ErrorLogPath is empty, refer to https://nginxui.com/guide/config-nginx.html for more information")
	ErrAccessLogPathIsEmpty                = e.New(50007, "settings.NginxLogSettings.AccessLogPath is empty, refer to https://nginxui.com/guide/config-nginx.html for more information")
	ErrEmptyLogLine                        = e.New(50008, "empty log line")
	ErrInvalidTimestamp                    = e.New(50009, "invalid timestamp format")
	ErrUnsupportedLogFormat                = e.New(50010, "unsupported log format")
	ErrIndexerNotAvailable                 = e.New(50011, "log indexer not available")
	ErrAnalyticsServiceNotAvailable        = e.New(50012, "analytics service not available")
	ErrLogFileNotExists                    = e.New(50013, "log file does not exist")
	ErrLogPathNotUnderWhitelist            = e.New(50014, "log path is not under whitelist")
	ErrCannotAccessLogFile                 = e.New(50015, "cannot access log file")
	ErrBackgroundServiceNotAvailable       = e.New(50016, "background log service not available")
	ErrFilePathRequired                    = e.New(50017, "file path is required")
	ErrFailedToRebuildIndex                = e.New(50018, "failed to rebuild index")
	ErrFailedToRebuildFileIndex            = e.New(50019, "failed to rebuild file index")
	ErrFailedToDeleteFileIndex             = e.New(50020, "failed to delete file index")
	ErrFailedToDeleteAllIndexes            = e.New(50021, "failed to delete all indexes")
	ErrFailedToGetIndexStats               = e.New(50022, "failed to get index status")
	ErrFailedToGetPersistenceStats         = e.New(50023, "failed to get persistence stats")
	ErrLogFileNotRegular                   = e.New(50024, "log file is not a regular file")
	ErrInvalidWebSocketMessageType         = e.New(50025, "invalid websocket message type")
	ErrModernSearcherNotAvailable          = e.New(50026, "modern searcher service not available")
	ErrModernAnalyticsNotAvailable         = e.New(50027, "modern analytics service not available")
	ErrModernIndexerNotAvailable           = e.New(50028, "modern indexer service not available")
)
