// This file is auto-generated by notification generator. DO NOT EDIT.
import type { ExternalNotifyConfig } from './types'

const DingTalkConfig: ExternalNotifyConfig = {
  name: () => $gettext('DingTalk'),
  config: [
    {
      key: 'access_token',
      label: 'Access Token',
    },
    {
      key: 'secret',
      label: 'Secret (Optional)',
    },
  ],
}

export default DingTalkConfig
