// This file is auto-generated by notification generator. DO NOT EDIT.
import type { ExternalNotifyConfig } from './types'

const GotifyConfig: ExternalNotifyConfig = {
  name: () => $gettext('Gotify'),
  config: [
    {
      key: 'url',
      label: 'URL',
    },
    {
      key: 'token',
      label: 'Token',
    },
    {
      key: 'priority',
      label: 'Priority',
    },
  ],
}

export default GotifyConfig
