// This file is auto-generated by notification generator. DO NOT EDIT.
import BarkConfig from './bark'
import DingTalkConfig from './dingtalk'
import TelegramConfig from './telegram'

const configMap = {
  bark: BarkConfig,
  dingtalk: DingTalkConfig,
  telegram: TelegramConfig,
}

export default configMap
