// This file is auto-generated by notification generator. DO NOT EDIT.
import type { ExternalNotifyConfig } from './types'

const TelegramConfig: ExternalNotifyConfig = {
  name: () => $gettext('Telegram'),
  config: [
    {
      key: 'bot_token',
      label: 'Bot Token',
    },
    {
      key: 'chat_id',
      label: 'Chat ID',
    },
    {
      key: 'http_proxy',
      label: 'HTTP Proxy',
    },
  ],
}

export default TelegramConfig
