// This file is auto-generated by notification generator. DO NOT EDIT.
import type { ExternalNotifyConfig } from './types'

const TelegramConfig: ExternalNotifyConfig = {
  name: () => $gettext('Telegram'),
  config: [
    {
      key: 'bot_token',
      label: () => $gettext('Bot Token'),
    },
    {
      key: 'chat_id',
      label: () => $gettext('Chat ID'),
    },
  ],
}

export default TelegramConfig
