export default {
  40001: () => $gettext('Access list name is required and must be a single line'),
  40002: () => $gettext('Identifier must use lowercase letters, digits and hyphens, and start with a letter or digit'),
  40003: () => $gettext('Identifier {0} is already used by another access list'),
  40004: () => $gettext('Unknown fallback {0}'),
  40005: () => $gettext('Rule {0} has an unknown type'),
  40006: () => $gettext('Rule {0}: {1} is not an IP address, CIDR, all or unix:'),
  40007: () => $gettext('Rule {0} references an access list that does not exist'),
  40008: () => $gettext('Rule {0} references the list itself'),
  40009: () => $gettext('Circular reference: {0}'),
  40401: () => $gettext('Access list not found'),
  40010: () => $gettext('Access list is still used by {0}'),
  40011: () => $gettext('Access list {0} does not exist'),
  40012: () => $gettext('The configuration could not be parsed'),
  40013: () => $gettext('Server block {0} not found'),
  40014: () => $gettext('Location {0} not found in server block {1}'),
  40015: () => $gettext('{0} contains allow or deny rules that were not written by Nginx UI; remove them first'),
  40016: () => $gettext('Unknown access mode {0}'),
  40017: () => $gettext('Rule {0}: the note must be a single line'),
  50001: () => $gettext('Nginx test failed: {0}'),
  50002: () => $gettext('Failed to write access list file: {0}'),
}
