export default {
  50001: () => $gettext('Filename is empty'),
  50002: () => $gettext('Cert path is not under the nginx conf dir'),
  50003: () => $gettext('Certificate decode error'),
  50004: () => $gettext('Certificate parse error'),
  50005: () => $gettext('Payload resource is nil'),
  50006: () => $gettext('Path: {0} is not under the nginx conf dir: {1}'),
  50007: () => $gettext('Certificate path is empty'),
  50008: () => $gettext('Get acme user error: {0}'),
  50009: () => $gettext('New transport error: {0}'),
  50010: () => $gettext('New lego client error: {0}'),
  50011: () => $gettext('Get dns credential error: {0}'),
  50012: () => $gettext('Provider not found: {0}'),
  50013: () => $gettext('Set env error: {0}'),
  50014: () => $gettext('New dns challenge provider error: {0}'),
  50015: () => $gettext('Environment configuration is empty'),
  50016: () => $gettext('Challenge error: {0}'),
  50017: () => $gettext('Set env flag to disable lego CNAME support error: {0}'),
  50018: () => $gettext('Renew cert error: {0}'),
  50019: () => $gettext('Make certificate dir error: {0}'),
  50020: () => $gettext('Write fullchain.cer error: {0}'),
  50021: () => $gettext('Write private.key error: {0}'),
  50022: () => $gettext('Obtain cert error: {0}'),
  50023: () => $gettext('Revoke cert error: {0}'),
  50031: () => $gettext('No certificate available'),
}
