export default {
  50001: () => $gettext('The log path is not under the paths in settings.NginxSettings.LogDirWhiteList'),
  50002: () => $gettext('ServerIdx out of range'),
  50003: () => $gettext('DirectiveIdx out of range'),
  50004: () => $gettext('Directive.Params neither access_log nor error_log'),
  50005: () => $gettext('Directive params is empty'),
  50006: () => $gettext('Settings.NginxLogSettings.ErrorLogPath is empty, refer to https://nginxui.com/guide/config-nginx.html for more information'),
  50007: () => $gettext('Settings.NginxLogSettings.AccessLogPath is empty, refer to https://nginxui.com/guide/config-nginx.html for more information'),
  50008: () => $gettext('Empty log line'),
  50009: () => $gettext('Invalid timestamp format'),
  50010: () => $gettext('Unsupported log format'),
  50011: () => $gettext('Log indexer not available'),
  50012: () => $gettext('Analytics service not available'),
  50013: () => $gettext('Log file does not exist'),
  50014: () => $gettext('Log path is not under whitelist'),
  50015: () => $gettext('Cannot access log file'),
  50016: () => $gettext('Background log service not available'),
  50017: () => $gettext('File path is required'),
  50018: () => $gettext('Failed to rebuild index'),
  50019: () => $gettext('Failed to rebuild file index'),
  50020: () => $gettext('Failed to delete file index'),
  50021: () => $gettext('Failed to delete all indexes'),
  50022: () => $gettext('Failed to get index status'),
  50023: () => $gettext('Failed to get persistence stats'),
  50024: () => $gettext('Log file is not a regular file'),
  50025: () => $gettext('Invalid websocket message type'),
}
