export default {
  55001: () => $gettext('Plugin manifest is invalid'),
  55002: () => $gettext('Plugin not found'),
  55003: () => $gettext('Plugin already exists'),
  55004: () => $gettext('Plugin is not running'),
  55005: () => $gettext('Plugin handshake failed'),
  55006: () => $gettext('Plugin has no executable for this platform'),
  55007: () => $gettext('Plugin package is invalid'),
  55008: () => $gettext('Plugin package is too large'),
  55009: () => $gettext('Plugin api version is incompatible'),
  55010: () => $gettext('Plugin permissions need approval'),
  55011: () => $gettext('Plugin dependency is missing: {0}'),
  55012: () => $gettext('Plugin dependencies form a cycle'),
  55013: () => $gettext('Plugin is in use by {0}'),
  55014: () => $gettext('Plugin system is disabled'),
  55015: () => $gettext('Plugin uploads are disabled'),
  55016: () => $gettext('Plugin call timed out'),
  55017: () => $gettext('Plugin rpc error: {0}'),
  55018: () => $gettext('Plugin setting {0} is invalid'),
  55019: () => $gettext('Plugin needs nginx-ui {0} or newer, this node runs {1}'),
  55020: () => $gettext('Plugin package declares another id'),
}
