export default {
  4040: () => $gettext('Task not found'),
  4041: () => $gettext('Failed to read nginx.conf'),
  5001: () => $gettext('Failed to parse nginx.conf'),
  4042: () => $gettext('Nginx conf no http block'),
  4043: () => $gettext('Nginx conf not include sites-enabled'),
  4044: () => $gettext('Nginx conf no stream block'),
  4045: () => $gettext('Nginx conf not include stream-enabled'),
  5002: () => $gettext('Failed to create backup'),
  4046: () => $gettext('Sites-available directory not exist'),
  4047: () => $gettext('Sites-enabled directory not exist'),
  4048: () => $gettext('Streams-available directory not exist'),
  4049: () => $gettext('Streams-enabled directory not exist'),
  4050: () => $gettext('Nginx conf not include conf.d directory'),
  4051: () => $gettext('Docker socket not exist'),
}
