export default {
  40400: () => $gettext('Task not found'),
  40401: () => $gettext('Task is not fixable'),
  40402: () => $gettext('Failed to read nginx.conf'),
  50001: () => $gettext('Failed to parse nginx.conf'),
  40403: () => $gettext('Nginx conf no http block'),
  40404: () => $gettext('Nginx conf not include sites-enabled'),
  40405: () => $gettext('Nginx conf no stream block'),
  40406: () => $gettext('Nginx conf not include stream-enabled'),
  50002: () => $gettext('Failed to create backup'),
  40407: () => $gettext('Sites-available directory not exist'),
  40408: () => $gettext('Sites-enabled directory not exist'),
  40409: () => $gettext('Streams-available directory not exist'),
  40410: () => $gettext('Streams-enabled directory not exist'),
  40411: () => $gettext('Nginx conf not include conf.d directory'),
  40412: () => $gettext('Docker socket not exist'),
  40413: () => $gettext('Config directory not exist'),
  40414: () => $gettext('Config entry file not exist'),
  40415: () => $gettext('PID path not exist'),
  40416: () => $gettext('Sbin path not exist'),
  40417: () => $gettext('Access log path not exist'),
  40418: () => $gettext('Error log path not exist'),
}
