export default {
  40001: () => $gettext('Invalid upstream name: use letters, digits, underscores and hyphens, starting with a letter or underscore (max 64 characters)'),
  40002: () => $gettext('Unsupported load balancing method: {0}'),
  40003: () => $gettext('The hash method needs a key'),
  40004: () => $gettext('Invalid hash key: {0}'),
  40005: () => $gettext('An upstream needs at least one server'),
  40006: () => $gettext('Invalid server address: {0}'),
  40007: () => $gettext('Server weight must be at least 1: {0}'),
  40008: () => $gettext('Server max_fails must not be negative: {0}'),
  40009: () => $gettext('Invalid server fail_timeout: {0}'),
  40010: () => $gettext('Backup servers cannot be used with the {0} method'),
  40011: () => $gettext('Keepalive must not be negative'),
  40012: () => $gettext('Additional directives must not contain blocks or braces'),
  40013: () => $gettext('Invalid server parameters: {0}'),
  40014: () => $gettext('Invalid shared memory zone size: {0}; use a number with a k or m suffix, at least 32k'),
  40015: () => $gettext('The shared memory zone is set by the zone switch; remove the zone directive from the additional directives'),
  40401: () => $gettext('Upstream not found: {0}'),
  40901: () => $gettext('Upstream already exists: {0}'),
  40902: () => $gettext('An upstream with this name is already defined in {0}'),
  40903: () => $gettext('Upstream is still referenced by: {0}'),
  40904: () => $gettext('{0} is not an upstream file managed by Nginx UI'),
  40905: () => $gettext('The shared memory zone {0} is already used by another directive; nginx reported: {1}'),
  50001: () => $gettext('The nginx conf.d directory is not available: {0}'),
}
