export default {
  40301: () => $gettext('Password incorrect'),
  40303: () => $gettext('User banned'),
  40304: () => $gettext('Invalid otp code'),
  40305: () => $gettext('Invalid recovery code'),
  40306: () => $gettext('Legacy recovery code not allowed since totp is not enabled'),
  50000: () => $gettext('WebAuthn settings are not configured'),
  50001: () => $gettext('User not enabled otp as 2fa'),
  50002: () => $gettext('Otp or recovery code empty'),
  50003: () => $gettext('Cannot remove initial user'),
  50004: () => $gettext('Cannot change initial user password in demo mode'),
  40401: () => $gettext('Session not found'),
  40402: () => $gettext('Token is empty'),
  50005: () => $gettext('Invalid claims type'),
  50006: () => $gettext('Config not found'),
  50007: () => $gettext('Db file not found'),
  50008: () => $gettext('Init user not exists'),
}
