package blocklist

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/0xJacky/Nginx-UI/internal/config"
	"github.com/0xJacky/Nginx-UI/internal/plugin"
	"github.com/0xJacky/Nginx-UI/model"
	"github.com/0xJacky/Nginx-UI/query"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/uozi-tech/cosy"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

const testKind = "plugin:test-feed"

// fakeFeed serves testKind with a list the test controls.
type fakeFeed struct {
	mu      sync.Mutex
	entries []Entry
	ttl     int
	err     error
	fetches int
}

func (f *fakeFeed) Kinds() []Kind {
	return []Kind{{Kind: testKind, Name: "Test feed", RefreshSeconds: 600, Fields: []KindField{
		{Key: "api_key", DisplayName: "API key", Required: true, Secret: true},
	}}}
}

func (f *fakeFeed) Fetch(_ context.Context, _ string, config map[string]string) (Result, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.fetches++
	if f.err != nil {
		return Result{}, f.err
	}
	if config["api_key"] == "" {
		return Result{}, cosy.WrapErrorWithParams(plugin.ErrBlocklistConfigInvalid, "api_key", "it is required")
	}
	return Result{Entries: append([]Entry(nil), f.entries...), TTLSeconds: f.ttl}, nil
}

func (f *fakeFeed) set(entries []Entry, ttl int, err error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.entries, f.ttl, f.err = entries, ttl, err
}

func (f *fakeFeed) fetchCount() int {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.fetches
}

var registerFeed = sync.OnceValue(func() *fakeFeed {
	feed := &fakeFeed{}
	RegisterSource(feed)
	return feed
})

// stubNginx stands in for nginx -t and the reload.
type stubNginx struct {
	mu       sync.Mutex
	reloads  int
	failTest bool
}

func (s *stubNginx) writer() config.GeneratedWriter {
	return config.GeneratedWriter{
		Test: func() error {
			s.mu.Lock()
			defer s.mu.Unlock()
			if s.failTest {
				return errors.New(`open() "blocklists/1.conf" failed`)
			}
			return nil
		},
		Reload: func() error {
			s.mu.Lock()
			defer s.mu.Unlock()
			s.reloads++
			return nil
		},
	}
}

func (s *stubNginx) reloadCount() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.reloads
}

func setupDB(t *testing.T) {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	require.NoError(t, err)
	sqlDB, err := db.DB()
	require.NoError(t, err)
	// The runs query from their own goroutines; one connection keeps them on
	// the same in-memory database.
	sqlDB.SetMaxOpenConns(1)
	require.NoError(t, db.AutoMigrate(&model.BlocklistSource{}))
	originalDB := model.UseDB()
	model.Use(db)
	query.SetDefault(db)
	t.Cleanup(func() {
		model.Use(originalDB)
		if originalDB != nil {
			query.SetDefault(originalDB)
		}
	})
}

// testRunner writes into a temporary configuration directory with a stubbed
// reload and a clock the test moves.
func testRunner(t *testing.T) (*Runner, *stubNginx, *time.Time, string) {
	t.Helper()
	confDir := t.TempDir()
	stub := &stubNginx{}
	now := time.Date(2026, 9, 23, 8, 0, 0, 0, time.UTC)
	r := NewRunner(t.Context(),
		WithWriter(stub.writer()),
		WithConfDir(func() string { return confDir }),
		WithClock(func() time.Time { return now }),
	)
	return r, stub, &now, confDir
}

func TestRender(t *testing.T) {
	rendered := Render([]Entry{
		{CIDR: "203.0.113.0/24"},
		{CIDR: " 198.51.100.23 "},
		{CIDR: "198.51.100.23/32"},
		{CIDR: "10.1.2.3/8"},
		{CIDR: "::ffff:192.0.2.1"},
		{CIDR: "2001:db8:bad::/48"},
		{CIDR: "0.0.0.0/0"},
		{CIDR: "::/0"},
		{CIDR: "fe80::1%eth0"},
		{CIDR: "example.com"},
		{CIDR: "10.0.0.1; allow all"},
		{CIDR: "1.2.3.4:80"},
		{CIDR: ""},
	})
	assert.Equal(t, strings.Join([]string{
		"# generated by nginx-ui",
		"# Refreshed from a blocklist source; changes to this file are overwritten.",
		"deny 10.0.0.0/8;",
		"deny 192.0.2.1;",
		"deny 198.51.100.23;",
		"deny 203.0.113.0/24;",
		"deny 2001:db8:bad::/48;",
		"",
	}, "\n"), string(rendered.Content))
	assert.Equal(t, 5, rendered.Written)
	assert.Equal(t, 7, rendered.Dropped)
	assert.Equal(t, 1, rendered.Duplicates)

	// The same set renders the same file whatever the order.
	again := Render([]Entry{{CIDR: "2001:db8:bad::/48"}, {CIDR: "10.0.0.0/8"}, {CIDR: "203.0.113.0/24"}, {CIDR: "192.0.2.1"}, {CIDR: "198.51.100.23"}})
	assert.Equal(t, string(rendered.Content), string(again.Content))

	empty := Render(nil)
	assert.Equal(t, "# generated by nginx-ui\n# Refreshed from a blocklist source; changes to this file are overwritten.\n", string(empty.Content))
}

func TestRunnerWritesAndReloadsOnlyOnChange(t *testing.T) {
	feed := registerFeed()
	setupDB(t)
	r, stub, now, confDir := testRunner(t)

	feed.set([]Entry{{CIDR: "203.0.113.0/24"}, {CIDR: "bogus"}}, 0, nil)
	source := &model.BlocklistSource{Name: "feed", Kind: testKind, Config: map[string]string{"api_key": "k"}, RefreshSeconds: 600, Enabled: true}
	disabled := &model.BlocklistSource{Name: "off", Kind: testKind, Config: map[string]string{"api_key": "k"}, RefreshSeconds: 600}
	require.NoError(t, query.BlocklistSource.Create(source, disabled))

	r.RefreshDue()
	path := filepath.Join(confDir, DirName, "1.conf")
	assert.Equal(t, path, r.Path(source.ID))
	content, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Contains(t, string(content), "deny 203.0.113.0/24;")
	assert.Equal(t, 1, stub.reloadCount())
	_, err = os.Stat(r.Path(disabled.ID))
	assert.True(t, os.IsNotExist(err), "a disabled source is not refreshed")

	stored, err := query.BlocklistSource.Where(query.BlocklistSource.ID.Eq(source.ID)).First()
	require.NoError(t, err)
	assert.Equal(t, model.RefreshStatusOK, stored.LastStatus)
	assert.Equal(t, 1, stored.EntryCount)
	assert.Contains(t, stored.LastMessage, "1 entries written")
	assert.Contains(t, stored.LastMessage, "1 invalid entries dropped")
	assert.Contains(t, stored.LastMessage, "nginx reloaded")
	require.NotNil(t, stored.NextRunAt)
	assert.True(t, stored.NextRunAt.Equal(now.Add(600*time.Second)))

	// Not due yet: nothing is fetched.
	fetches := feed.fetchCount()
	*now = now.Add(time.Minute)
	r.RefreshDue()
	assert.Equal(t, fetches, feed.fetchCount())

	// Due, same list: no reload.
	*now = now.Add(10 * time.Minute)
	r.RefreshDue()
	assert.Equal(t, fetches+1, feed.fetchCount())
	assert.Equal(t, 1, stub.reloadCount())
	stored, err = query.BlocklistSource.Where(query.BlocklistSource.ID.Eq(source.ID)).First()
	require.NoError(t, err)
	assert.Contains(t, stored.LastMessage, "no change")

	// A shorter ttl of the source brings the next run forward, but never
	// below a minute.
	feed.set([]Entry{{CIDR: "203.0.113.0/24"}, {CIDR: "198.51.100.7"}}, 30, nil)
	stored, err = r.Refresh(t.Context(), source.ID)
	require.NoError(t, err)
	assert.Equal(t, 2, stored.EntryCount)
	assert.Equal(t, 2, stub.reloadCount())
	assert.True(t, stored.NextRunAt.Equal(now.Add(time.Minute)), "next run %v", stored.NextRunAt)
}

func TestRunnerKeepsTheFileWhenAFetchFails(t *testing.T) {
	feed := registerFeed()
	setupDB(t)
	r, stub, now, _ := testRunner(t)

	feed.set([]Entry{{CIDR: "203.0.113.0/24"}}, 0, nil)
	source := &model.BlocklistSource{Name: "feed", Kind: testKind, Config: map[string]string{"api_key": "k"}, RefreshSeconds: 86400, Enabled: true}
	require.NoError(t, query.BlocklistSource.Create(source))
	_, err := r.Refresh(t.Context(), source.ID)
	require.NoError(t, err)
	before, err := os.ReadFile(r.Path(source.ID))
	require.NoError(t, err)

	feed.set(nil, 0, errors.New("feed is down"))
	stored, err := r.Refresh(t.Context(), source.ID)
	require.NoError(t, err)
	assert.Equal(t, model.RefreshStatusFailed, stored.LastStatus)
	assert.Contains(t, stored.LastMessage, "feed is down")
	assert.Equal(t, 1, stored.EntryCount, "the count of the kept file stays")
	assert.True(t, stored.NextRunAt.Equal(now.Add(retryAfterFailure)), "a failure is retried within five minutes")
	after, err := os.ReadFile(r.Path(source.ID))
	require.NoError(t, err)
	assert.Equal(t, string(before), string(after))
	assert.Equal(t, 1, stub.reloadCount())

	// nginx rejecting the file is a failure too, and the file is put back.
	feed.set([]Entry{{CIDR: "198.51.100.0/24"}}, 0, nil)
	stub.failTest = true
	stored, err = r.Refresh(t.Context(), source.ID)
	require.NoError(t, err)
	assert.Equal(t, model.RefreshStatusFailed, stored.LastStatus)
	assert.Contains(t, stored.LastMessage, "could not apply")
	after, err = os.ReadFile(r.Path(source.ID))
	require.NoError(t, err)
	assert.Equal(t, string(before), string(after))
}

func TestRunnerRemove(t *testing.T) {
	feed := registerFeed()
	setupDB(t)
	r, stub, _, _ := testRunner(t)

	feed.set([]Entry{{CIDR: "203.0.113.0/24"}}, 0, nil)
	source := &model.BlocklistSource{Name: "feed", Kind: testKind, Config: map[string]string{"api_key": "k"}, RefreshSeconds: 600, Enabled: true}
	require.NoError(t, query.BlocklistSource.Create(source))
	_, err := r.Refresh(t.Context(), source.ID)
	require.NoError(t, err)

	stub.failTest = true
	err = r.Remove(source.ID)
	var cosyErr *cosy.Error
	require.ErrorAs(t, err, &cosyErr)
	assert.Equal(t, int32(55213), cosyErr.Code)
	assert.FileExists(t, r.Path(source.ID))

	stub.failTest = false
	require.NoError(t, r.Remove(source.ID))
	assert.NoFileExists(t, r.Path(source.ID))
	require.NoError(t, r.Remove(source.ID), "removing a missing file is fine")
}

func TestRegistry(t *testing.T) {
	registerFeed()
	kind, ok := KindOf(testKind)
	require.True(t, ok)
	assert.Equal(t, 600, kind.RefreshSeconds)
	assert.NoError(t, ValidateConfig(testKind, map[string]string{"api_key": "k"}))

	var cosyErr *cosy.Error
	require.ErrorAs(t, ValidateConfig(testKind, map[string]string{}), &cosyErr)
	assert.Equal(t, int32(55206), cosyErr.Code)
	require.ErrorAs(t, ValidateConfig("plugin:gone", nil), &cosyErr)
	assert.Equal(t, int32(55205), cosyErr.Code)
	require.ErrorAs(t, ValidateConfig("Not A Kind", nil), &cosyErr)
	assert.Equal(t, int32(55205), cosyErr.Code)

	assert.Equal(t, "include blocklists/7.conf;", IncludeLine(7))
}

func TestNextInterval(t *testing.T) {
	assert.Equal(t, time.Hour, nextInterval(0, 0, false))
	assert.Equal(t, 10*time.Minute, nextInterval(600, 0, false))
	assert.Equal(t, 2*time.Minute, nextInterval(600, 120, false))
	assert.Equal(t, time.Minute, nextInterval(600, 5, false))
	assert.Equal(t, 10*time.Minute, nextInterval(600, 3600, false))
	assert.Equal(t, 5*time.Minute, nextInterval(86400, 0, true))
	assert.Equal(t, 2*time.Minute, nextInterval(120, 0, true))
}
