// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/0xJacky/Nginx-UI/model"
)

func newAccessList(db *gorm.DB, opts ...gen.DOOption) accessList {
	_accessList := accessList{}

	_accessList.accessListDo.UseDB(db, opts...)
	_accessList.accessListDo.UseModel(&model.AccessList{})

	tableName := _accessList.accessListDo.TableName()
	_accessList.ALL = field.NewAsterisk(tableName)
	_accessList.ID = field.NewUint64(tableName, "id")
	_accessList.CreatedAt = field.NewTime(tableName, "created_at")
	_accessList.UpdatedAt = field.NewTime(tableName, "updated_at")
	_accessList.DeletedAt = field.NewField(tableName, "deleted_at")
	_accessList.Name = field.NewString(tableName, "name")
	_accessList.Slug = field.NewString(tableName, "slug")
	_accessList.Rules = field.NewField(tableName, "rules")
	_accessList.Fallback = field.NewString(tableName, "fallback")

	_accessList.fillFieldMap()

	return _accessList
}

type accessList struct {
	accessListDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Name      field.String
	Slug      field.String
	Rules     field.Field
	Fallback  field.String

	fieldMap map[string]field.Expr
}

func (a accessList) Table(newTableName string) *accessList {
	a.accessListDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accessList) As(alias string) *accessList {
	a.accessListDo.DO = *(a.accessListDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accessList) updateTableName(table string) *accessList {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Name = field.NewString(table, "name")
	a.Slug = field.NewString(table, "slug")
	a.Rules = field.NewField(table, "rules")
	a.Fallback = field.NewString(table, "fallback")

	a.fillFieldMap()

	return a
}

func (a *accessList) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accessList) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["name"] = a.Name
	a.fieldMap["slug"] = a.Slug
	a.fieldMap["rules"] = a.Rules
	a.fieldMap["fallback"] = a.Fallback
}

func (a accessList) clone(db *gorm.DB) accessList {
	a.accessListDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accessList) replaceDB(db *gorm.DB) accessList {
	a.accessListDo.ReplaceDB(db)
	return a
}

type accessListDo struct{ gen.DO }

// FirstByID Where("id=@id")
func (a accessListDo) FirstByID(id uint64) (result *model.AccessList, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("id=? ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Where(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DeleteByID update @@table set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=@id
func (a accessListDo) DeleteByID(id uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("update access_lists set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=? ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (a accessListDo) Debug() *accessListDo {
	return a.withDO(a.DO.Debug())
}

func (a accessListDo) WithContext(ctx context.Context) *accessListDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accessListDo) ReadDB() *accessListDo {
	return a.Clauses(dbresolver.Read)
}

func (a accessListDo) WriteDB() *accessListDo {
	return a.Clauses(dbresolver.Write)
}

func (a accessListDo) Session(config *gorm.Session) *accessListDo {
	return a.withDO(a.DO.Session(config))
}

func (a accessListDo) Clauses(conds ...clause.Expression) *accessListDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accessListDo) Returning(value interface{}, columns ...string) *accessListDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accessListDo) Not(conds ...gen.Condition) *accessListDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accessListDo) Or(conds ...gen.Condition) *accessListDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accessListDo) Select(conds ...field.Expr) *accessListDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accessListDo) Where(conds ...gen.Condition) *accessListDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accessListDo) Order(conds ...field.Expr) *accessListDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accessListDo) Distinct(cols ...field.Expr) *accessListDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accessListDo) Omit(cols ...field.Expr) *accessListDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accessListDo) Join(table schema.Tabler, on ...field.Expr) *accessListDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accessListDo) LeftJoin(table schema.Tabler, on ...field.Expr) *accessListDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accessListDo) RightJoin(table schema.Tabler, on ...field.Expr) *accessListDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accessListDo) Group(cols ...field.Expr) *accessListDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accessListDo) Having(conds ...gen.Condition) *accessListDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accessListDo) Limit(limit int) *accessListDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accessListDo) Offset(offset int) *accessListDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accessListDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *accessListDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accessListDo) Unscoped() *accessListDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accessListDo) Create(values ...*model.AccessList) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accessListDo) CreateInBatches(values []*model.AccessList, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accessListDo) Save(values ...*model.AccessList) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accessListDo) First() (*model.AccessList, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessList), nil
	}
}

func (a accessListDo) Take() (*model.AccessList, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessList), nil
	}
}

func (a accessListDo) Last() (*model.AccessList, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessList), nil
	}
}

func (a accessListDo) Find() ([]*model.AccessList, error) {
	result, err := a.DO.Find()
	return result.([]*model.AccessList), err
}

func (a accessListDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccessList, err error) {
	buf := make([]*model.AccessList, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accessListDo) FindInBatches(result *[]*model.AccessList, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accessListDo) Attrs(attrs ...field.AssignExpr) *accessListDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accessListDo) Assign(attrs ...field.AssignExpr) *accessListDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accessListDo) Joins(fields ...field.RelationField) *accessListDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accessListDo) Preload(fields ...field.RelationField) *accessListDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accessListDo) FirstOrInit() (*model.AccessList, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessList), nil
	}
}

func (a accessListDo) FirstOrCreate() (*model.AccessList, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccessList), nil
	}
}

func (a accessListDo) FindByPage(offset int, limit int) (result []*model.AccessList, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accessListDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accessListDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accessListDo) Delete(models ...*model.AccessList) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accessListDo) withDO(do gen.Dao) *accessListDo {
	a.DO = *do.(*gen.DO)
	return a
}
