// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/0xJacky/Nginx-UI/model"
)

func newCertDeployTarget(db *gorm.DB, opts ...gen.DOOption) certDeployTarget {
	_certDeployTarget := certDeployTarget{}

	_certDeployTarget.certDeployTargetDo.UseDB(db, opts...)
	_certDeployTarget.certDeployTargetDo.UseModel(&model.CertDeployTarget{})

	tableName := _certDeployTarget.certDeployTargetDo.TableName()
	_certDeployTarget.ALL = field.NewAsterisk(tableName)
	_certDeployTarget.ID = field.NewUint64(tableName, "id")
	_certDeployTarget.CreatedAt = field.NewTime(tableName, "created_at")
	_certDeployTarget.UpdatedAt = field.NewTime(tableName, "updated_at")
	_certDeployTarget.DeletedAt = field.NewField(tableName, "deleted_at")
	_certDeployTarget.Name = field.NewString(tableName, "name")
	_certDeployTarget.Kind = field.NewString(tableName, "kind")
	_certDeployTarget.Config = field.NewField(tableName, "config")
	_certDeployTarget.CertID = field.NewUint64(tableName, "cert_id")
	_certDeployTarget.Enabled = field.NewBool(tableName, "enabled")

	_certDeployTarget.fillFieldMap()

	return _certDeployTarget
}

type certDeployTarget struct {
	certDeployTargetDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Name      field.String
	Kind      field.String
	Config    field.Field
	CertID    field.Uint64
	Enabled   field.Bool

	fieldMap map[string]field.Expr
}

func (c certDeployTarget) Table(newTableName string) *certDeployTarget {
	c.certDeployTargetDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c certDeployTarget) As(alias string) *certDeployTarget {
	c.certDeployTargetDo.DO = *(c.certDeployTargetDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *certDeployTarget) updateTableName(table string) *certDeployTarget {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.Name = field.NewString(table, "name")
	c.Kind = field.NewString(table, "kind")
	c.Config = field.NewField(table, "config")
	c.CertID = field.NewUint64(table, "cert_id")
	c.Enabled = field.NewBool(table, "enabled")

	c.fillFieldMap()

	return c
}

func (c *certDeployTarget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *certDeployTarget) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["name"] = c.Name
	c.fieldMap["kind"] = c.Kind
	c.fieldMap["config"] = c.Config
	c.fieldMap["cert_id"] = c.CertID
	c.fieldMap["enabled"] = c.Enabled
}

func (c certDeployTarget) clone(db *gorm.DB) certDeployTarget {
	c.certDeployTargetDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c certDeployTarget) replaceDB(db *gorm.DB) certDeployTarget {
	c.certDeployTargetDo.ReplaceDB(db)
	return c
}

type certDeployTargetDo struct{ gen.DO }

// FirstByID Where("id=@id")
func (c certDeployTargetDo) FirstByID(id uint64) (result *model.CertDeployTarget, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("id=? ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Where(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DeleteByID update @@table set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=@id
func (c certDeployTargetDo) DeleteByID(id uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("update cert_deploy_targets set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=? ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (c certDeployTargetDo) Debug() *certDeployTargetDo {
	return c.withDO(c.DO.Debug())
}

func (c certDeployTargetDo) WithContext(ctx context.Context) *certDeployTargetDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c certDeployTargetDo) ReadDB() *certDeployTargetDo {
	return c.Clauses(dbresolver.Read)
}

func (c certDeployTargetDo) WriteDB() *certDeployTargetDo {
	return c.Clauses(dbresolver.Write)
}

func (c certDeployTargetDo) Session(config *gorm.Session) *certDeployTargetDo {
	return c.withDO(c.DO.Session(config))
}

func (c certDeployTargetDo) Clauses(conds ...clause.Expression) *certDeployTargetDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c certDeployTargetDo) Returning(value interface{}, columns ...string) *certDeployTargetDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c certDeployTargetDo) Not(conds ...gen.Condition) *certDeployTargetDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c certDeployTargetDo) Or(conds ...gen.Condition) *certDeployTargetDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c certDeployTargetDo) Select(conds ...field.Expr) *certDeployTargetDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c certDeployTargetDo) Where(conds ...gen.Condition) *certDeployTargetDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c certDeployTargetDo) Order(conds ...field.Expr) *certDeployTargetDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c certDeployTargetDo) Distinct(cols ...field.Expr) *certDeployTargetDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c certDeployTargetDo) Omit(cols ...field.Expr) *certDeployTargetDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c certDeployTargetDo) Join(table schema.Tabler, on ...field.Expr) *certDeployTargetDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c certDeployTargetDo) LeftJoin(table schema.Tabler, on ...field.Expr) *certDeployTargetDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c certDeployTargetDo) RightJoin(table schema.Tabler, on ...field.Expr) *certDeployTargetDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c certDeployTargetDo) Group(cols ...field.Expr) *certDeployTargetDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c certDeployTargetDo) Having(conds ...gen.Condition) *certDeployTargetDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c certDeployTargetDo) Limit(limit int) *certDeployTargetDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c certDeployTargetDo) Offset(offset int) *certDeployTargetDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c certDeployTargetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *certDeployTargetDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c certDeployTargetDo) Unscoped() *certDeployTargetDo {
	return c.withDO(c.DO.Unscoped())
}

func (c certDeployTargetDo) Create(values ...*model.CertDeployTarget) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c certDeployTargetDo) CreateInBatches(values []*model.CertDeployTarget, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c certDeployTargetDo) Save(values ...*model.CertDeployTarget) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c certDeployTargetDo) First() (*model.CertDeployTarget, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertDeployTarget), nil
	}
}

func (c certDeployTargetDo) Take() (*model.CertDeployTarget, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertDeployTarget), nil
	}
}

func (c certDeployTargetDo) Last() (*model.CertDeployTarget, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertDeployTarget), nil
	}
}

func (c certDeployTargetDo) Find() ([]*model.CertDeployTarget, error) {
	result, err := c.DO.Find()
	return result.([]*model.CertDeployTarget), err
}

func (c certDeployTargetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CertDeployTarget, err error) {
	buf := make([]*model.CertDeployTarget, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c certDeployTargetDo) FindInBatches(result *[]*model.CertDeployTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c certDeployTargetDo) Attrs(attrs ...field.AssignExpr) *certDeployTargetDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c certDeployTargetDo) Assign(attrs ...field.AssignExpr) *certDeployTargetDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c certDeployTargetDo) Joins(fields ...field.RelationField) *certDeployTargetDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c certDeployTargetDo) Preload(fields ...field.RelationField) *certDeployTargetDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c certDeployTargetDo) FirstOrInit() (*model.CertDeployTarget, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertDeployTarget), nil
	}
}

func (c certDeployTargetDo) FirstOrCreate() (*model.CertDeployTarget, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertDeployTarget), nil
	}
}

func (c certDeployTargetDo) FindByPage(offset int, limit int) (result []*model.CertDeployTarget, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c certDeployTargetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c certDeployTargetDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c certDeployTargetDo) Delete(models ...*model.CertDeployTarget) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *certDeployTargetDo) withDO(do gen.Dao) *certDeployTargetDo {
	c.DO = *do.(*gen.DO)
	return c
}
