// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/0xJacky/Nginx-UI/model"
)

func newNodeControllerCredential(db *gorm.DB, opts ...gen.DOOption) nodeControllerCredential {
	_nodeControllerCredential := nodeControllerCredential{}

	_nodeControllerCredential.nodeControllerCredentialDo.UseDB(db, opts...)
	_nodeControllerCredential.nodeControllerCredentialDo.UseModel(&model.NodeControllerCredential{})

	tableName := _nodeControllerCredential.nodeControllerCredentialDo.TableName()
	_nodeControllerCredential.ALL = field.NewAsterisk(tableName)
	_nodeControllerCredential.ID = field.NewUint64(tableName, "id")
	_nodeControllerCredential.CreatedAt = field.NewTime(tableName, "created_at")
	_nodeControllerCredential.UpdatedAt = field.NewTime(tableName, "updated_at")
	_nodeControllerCredential.DeletedAt = field.NewField(tableName, "deleted_at")
	_nodeControllerCredential.CredentialID = field.NewString(tableName, "credential_id")
	_nodeControllerCredential.ControllerInstanceID = field.NewString(tableName, "controller_instance_id")
	_nodeControllerCredential.PublicKey = field.NewBytes(tableName, "public_key")
	_nodeControllerCredential.PreviousPublicKey = field.NewBytes(tableName, "previous_public_key")
	_nodeControllerCredential.PreviousValidUntil = field.NewTime(tableName, "previous_valid_until")
	_nodeControllerCredential.PendingPublicKey = field.NewBytes(tableName, "pending_public_key")
	_nodeControllerCredential.Status = field.NewString(tableName, "status")
	_nodeControllerCredential.LastUsedAt = field.NewTime(tableName, "last_used_at")
	_nodeControllerCredential.RevokedAt = field.NewTime(tableName, "revoked_at")

	_nodeControllerCredential.fillFieldMap()

	return _nodeControllerCredential
}

type nodeControllerCredential struct {
	nodeControllerCredentialDo

	ALL                  field.Asterisk
	ID                   field.Uint64
	CreatedAt            field.Time
	UpdatedAt            field.Time
	DeletedAt            field.Field
	CredentialID         field.String
	ControllerInstanceID field.String
	PublicKey            field.Bytes
	PreviousPublicKey    field.Bytes
	PreviousValidUntil   field.Time
	PendingPublicKey     field.Bytes
	Status               field.String
	LastUsedAt           field.Time
	RevokedAt            field.Time

	fieldMap map[string]field.Expr
}

func (n nodeControllerCredential) Table(newTableName string) *nodeControllerCredential {
	n.nodeControllerCredentialDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeControllerCredential) As(alias string) *nodeControllerCredential {
	n.nodeControllerCredentialDo.DO = *(n.nodeControllerCredentialDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeControllerCredential) updateTableName(table string) *nodeControllerCredential {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewUint64(table, "id")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.DeletedAt = field.NewField(table, "deleted_at")
	n.CredentialID = field.NewString(table, "credential_id")
	n.ControllerInstanceID = field.NewString(table, "controller_instance_id")
	n.PublicKey = field.NewBytes(table, "public_key")
	n.PreviousPublicKey = field.NewBytes(table, "previous_public_key")
	n.PreviousValidUntil = field.NewTime(table, "previous_valid_until")
	n.PendingPublicKey = field.NewBytes(table, "pending_public_key")
	n.Status = field.NewString(table, "status")
	n.LastUsedAt = field.NewTime(table, "last_used_at")
	n.RevokedAt = field.NewTime(table, "revoked_at")

	n.fillFieldMap()

	return n
}

func (n *nodeControllerCredential) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeControllerCredential) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 13)
	n.fieldMap["id"] = n.ID
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["deleted_at"] = n.DeletedAt
	n.fieldMap["credential_id"] = n.CredentialID
	n.fieldMap["controller_instance_id"] = n.ControllerInstanceID
	n.fieldMap["public_key"] = n.PublicKey
	n.fieldMap["previous_public_key"] = n.PreviousPublicKey
	n.fieldMap["previous_valid_until"] = n.PreviousValidUntil
	n.fieldMap["pending_public_key"] = n.PendingPublicKey
	n.fieldMap["status"] = n.Status
	n.fieldMap["last_used_at"] = n.LastUsedAt
	n.fieldMap["revoked_at"] = n.RevokedAt
}

func (n nodeControllerCredential) clone(db *gorm.DB) nodeControllerCredential {
	n.nodeControllerCredentialDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeControllerCredential) replaceDB(db *gorm.DB) nodeControllerCredential {
	n.nodeControllerCredentialDo.ReplaceDB(db)
	return n
}

type nodeControllerCredentialDo struct{ gen.DO }

// FirstByID Where("id=@id")
func (n nodeControllerCredentialDo) FirstByID(id uint64) (result *model.NodeControllerCredential, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("id=? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Where(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DeleteByID update @@table set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=@id
func (n nodeControllerCredentialDo) DeleteByID(id uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("update node_controller_credentials set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (n nodeControllerCredentialDo) Debug() *nodeControllerCredentialDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeControllerCredentialDo) WithContext(ctx context.Context) *nodeControllerCredentialDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeControllerCredentialDo) ReadDB() *nodeControllerCredentialDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeControllerCredentialDo) WriteDB() *nodeControllerCredentialDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeControllerCredentialDo) Session(config *gorm.Session) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeControllerCredentialDo) Clauses(conds ...clause.Expression) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeControllerCredentialDo) Returning(value interface{}, columns ...string) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeControllerCredentialDo) Not(conds ...gen.Condition) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeControllerCredentialDo) Or(conds ...gen.Condition) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeControllerCredentialDo) Select(conds ...field.Expr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeControllerCredentialDo) Where(conds ...gen.Condition) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeControllerCredentialDo) Order(conds ...field.Expr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeControllerCredentialDo) Distinct(cols ...field.Expr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeControllerCredentialDo) Omit(cols ...field.Expr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeControllerCredentialDo) Join(table schema.Tabler, on ...field.Expr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeControllerCredentialDo) LeftJoin(table schema.Tabler, on ...field.Expr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeControllerCredentialDo) RightJoin(table schema.Tabler, on ...field.Expr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeControllerCredentialDo) Group(cols ...field.Expr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeControllerCredentialDo) Having(conds ...gen.Condition) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeControllerCredentialDo) Limit(limit int) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeControllerCredentialDo) Offset(offset int) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeControllerCredentialDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeControllerCredentialDo) Unscoped() *nodeControllerCredentialDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeControllerCredentialDo) Create(values ...*model.NodeControllerCredential) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeControllerCredentialDo) CreateInBatches(values []*model.NodeControllerCredential, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeControllerCredentialDo) Save(values ...*model.NodeControllerCredential) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeControllerCredentialDo) First() (*model.NodeControllerCredential, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeControllerCredential), nil
	}
}

func (n nodeControllerCredentialDo) Take() (*model.NodeControllerCredential, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeControllerCredential), nil
	}
}

func (n nodeControllerCredentialDo) Last() (*model.NodeControllerCredential, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeControllerCredential), nil
	}
}

func (n nodeControllerCredentialDo) Find() ([]*model.NodeControllerCredential, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeControllerCredential), err
}

func (n nodeControllerCredentialDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeControllerCredential, err error) {
	buf := make([]*model.NodeControllerCredential, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeControllerCredentialDo) FindInBatches(result *[]*model.NodeControllerCredential, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeControllerCredentialDo) Attrs(attrs ...field.AssignExpr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeControllerCredentialDo) Assign(attrs ...field.AssignExpr) *nodeControllerCredentialDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeControllerCredentialDo) Joins(fields ...field.RelationField) *nodeControllerCredentialDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeControllerCredentialDo) Preload(fields ...field.RelationField) *nodeControllerCredentialDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeControllerCredentialDo) FirstOrInit() (*model.NodeControllerCredential, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeControllerCredential), nil
	}
}

func (n nodeControllerCredentialDo) FirstOrCreate() (*model.NodeControllerCredential, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeControllerCredential), nil
	}
}

func (n nodeControllerCredentialDo) FindByPage(offset int, limit int) (result []*model.NodeControllerCredential, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeControllerCredentialDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeControllerCredentialDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeControllerCredentialDo) Delete(models ...*model.NodeControllerCredential) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeControllerCredentialDo) withDO(do gen.Dao) *nodeControllerCredentialDo {
	n.DO = *do.(*gen.DO)
	return n
}
