// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/0xJacky/Nginx-UI/model"
)

func newNodeCredential(db *gorm.DB, opts ...gen.DOOption) nodeCredential {
	_nodeCredential := nodeCredential{}

	_nodeCredential.nodeCredentialDo.UseDB(db, opts...)
	_nodeCredential.nodeCredentialDo.UseModel(&model.NodeCredential{})

	tableName := _nodeCredential.nodeCredentialDo.TableName()
	_nodeCredential.ALL = field.NewAsterisk(tableName)
	_nodeCredential.ID = field.NewUint64(tableName, "id")
	_nodeCredential.CreatedAt = field.NewTime(tableName, "created_at")
	_nodeCredential.UpdatedAt = field.NewTime(tableName, "updated_at")
	_nodeCredential.DeletedAt = field.NewField(tableName, "deleted_at")
	_nodeCredential.NodeID = field.NewUint64(tableName, "node_id")
	_nodeCredential.CredentialID = field.NewString(tableName, "credential_id")
	_nodeCredential.TargetInstanceID = field.NewString(tableName, "target_instance_id")
	_nodeCredential.PublicKey = field.NewBytes(tableName, "public_key")
	_nodeCredential.EncryptedPrivateKey = field.NewBytes(tableName, "encrypted_private_key")
	_nodeCredential.PreviousPublicKey = field.NewBytes(tableName, "previous_public_key")
	_nodeCredential.EncryptedPreviousPrivateKey = field.NewBytes(tableName, "encrypted_previous_private_key")
	_nodeCredential.PreviousValidUntil = field.NewTime(tableName, "previous_valid_until")
	_nodeCredential.PendingPublicKey = field.NewBytes(tableName, "pending_public_key")
	_nodeCredential.EncryptedPendingPrivateKey = field.NewBytes(tableName, "encrypted_pending_private_key")
	_nodeCredential.Status = field.NewString(tableName, "status")
	_nodeCredential.RotatedAt = field.NewTime(tableName, "rotated_at")
	_nodeCredential.LastUsedAt = field.NewTime(tableName, "last_used_at")
	_nodeCredential.RevokedAt = field.NewTime(tableName, "revoked_at")

	_nodeCredential.fillFieldMap()

	return _nodeCredential
}

type nodeCredential struct {
	nodeCredentialDo

	ALL                         field.Asterisk
	ID                          field.Uint64
	CreatedAt                   field.Time
	UpdatedAt                   field.Time
	DeletedAt                   field.Field
	NodeID                      field.Uint64
	CredentialID                field.String
	TargetInstanceID            field.String
	PublicKey                   field.Bytes
	EncryptedPrivateKey         field.Bytes
	PreviousPublicKey           field.Bytes
	EncryptedPreviousPrivateKey field.Bytes
	PreviousValidUntil          field.Time
	PendingPublicKey            field.Bytes
	EncryptedPendingPrivateKey  field.Bytes
	Status                      field.String
	RotatedAt                   field.Time
	LastUsedAt                  field.Time
	RevokedAt                   field.Time

	fieldMap map[string]field.Expr
}

func (n nodeCredential) Table(newTableName string) *nodeCredential {
	n.nodeCredentialDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeCredential) As(alias string) *nodeCredential {
	n.nodeCredentialDo.DO = *(n.nodeCredentialDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeCredential) updateTableName(table string) *nodeCredential {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewUint64(table, "id")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.DeletedAt = field.NewField(table, "deleted_at")
	n.NodeID = field.NewUint64(table, "node_id")
	n.CredentialID = field.NewString(table, "credential_id")
	n.TargetInstanceID = field.NewString(table, "target_instance_id")
	n.PublicKey = field.NewBytes(table, "public_key")
	n.EncryptedPrivateKey = field.NewBytes(table, "encrypted_private_key")
	n.PreviousPublicKey = field.NewBytes(table, "previous_public_key")
	n.EncryptedPreviousPrivateKey = field.NewBytes(table, "encrypted_previous_private_key")
	n.PreviousValidUntil = field.NewTime(table, "previous_valid_until")
	n.PendingPublicKey = field.NewBytes(table, "pending_public_key")
	n.EncryptedPendingPrivateKey = field.NewBytes(table, "encrypted_pending_private_key")
	n.Status = field.NewString(table, "status")
	n.RotatedAt = field.NewTime(table, "rotated_at")
	n.LastUsedAt = field.NewTime(table, "last_used_at")
	n.RevokedAt = field.NewTime(table, "revoked_at")

	n.fillFieldMap()

	return n
}

func (n *nodeCredential) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeCredential) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 18)
	n.fieldMap["id"] = n.ID
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["deleted_at"] = n.DeletedAt
	n.fieldMap["node_id"] = n.NodeID
	n.fieldMap["credential_id"] = n.CredentialID
	n.fieldMap["target_instance_id"] = n.TargetInstanceID
	n.fieldMap["public_key"] = n.PublicKey
	n.fieldMap["encrypted_private_key"] = n.EncryptedPrivateKey
	n.fieldMap["previous_public_key"] = n.PreviousPublicKey
	n.fieldMap["encrypted_previous_private_key"] = n.EncryptedPreviousPrivateKey
	n.fieldMap["previous_valid_until"] = n.PreviousValidUntil
	n.fieldMap["pending_public_key"] = n.PendingPublicKey
	n.fieldMap["encrypted_pending_private_key"] = n.EncryptedPendingPrivateKey
	n.fieldMap["status"] = n.Status
	n.fieldMap["rotated_at"] = n.RotatedAt
	n.fieldMap["last_used_at"] = n.LastUsedAt
	n.fieldMap["revoked_at"] = n.RevokedAt
}

func (n nodeCredential) clone(db *gorm.DB) nodeCredential {
	n.nodeCredentialDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeCredential) replaceDB(db *gorm.DB) nodeCredential {
	n.nodeCredentialDo.ReplaceDB(db)
	return n
}

type nodeCredentialDo struct{ gen.DO }

// FirstByID Where("id=@id")
func (n nodeCredentialDo) FirstByID(id uint64) (result *model.NodeCredential, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("id=? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Where(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DeleteByID update @@table set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=@id
func (n nodeCredentialDo) DeleteByID(id uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("update node_credentials set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (n nodeCredentialDo) Debug() *nodeCredentialDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeCredentialDo) WithContext(ctx context.Context) *nodeCredentialDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeCredentialDo) ReadDB() *nodeCredentialDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeCredentialDo) WriteDB() *nodeCredentialDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeCredentialDo) Session(config *gorm.Session) *nodeCredentialDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeCredentialDo) Clauses(conds ...clause.Expression) *nodeCredentialDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeCredentialDo) Returning(value interface{}, columns ...string) *nodeCredentialDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeCredentialDo) Not(conds ...gen.Condition) *nodeCredentialDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeCredentialDo) Or(conds ...gen.Condition) *nodeCredentialDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeCredentialDo) Select(conds ...field.Expr) *nodeCredentialDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeCredentialDo) Where(conds ...gen.Condition) *nodeCredentialDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeCredentialDo) Order(conds ...field.Expr) *nodeCredentialDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeCredentialDo) Distinct(cols ...field.Expr) *nodeCredentialDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeCredentialDo) Omit(cols ...field.Expr) *nodeCredentialDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeCredentialDo) Join(table schema.Tabler, on ...field.Expr) *nodeCredentialDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeCredentialDo) LeftJoin(table schema.Tabler, on ...field.Expr) *nodeCredentialDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeCredentialDo) RightJoin(table schema.Tabler, on ...field.Expr) *nodeCredentialDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeCredentialDo) Group(cols ...field.Expr) *nodeCredentialDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeCredentialDo) Having(conds ...gen.Condition) *nodeCredentialDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeCredentialDo) Limit(limit int) *nodeCredentialDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeCredentialDo) Offset(offset int) *nodeCredentialDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeCredentialDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *nodeCredentialDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeCredentialDo) Unscoped() *nodeCredentialDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeCredentialDo) Create(values ...*model.NodeCredential) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeCredentialDo) CreateInBatches(values []*model.NodeCredential, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeCredentialDo) Save(values ...*model.NodeCredential) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeCredentialDo) First() (*model.NodeCredential, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeCredential), nil
	}
}

func (n nodeCredentialDo) Take() (*model.NodeCredential, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeCredential), nil
	}
}

func (n nodeCredentialDo) Last() (*model.NodeCredential, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeCredential), nil
	}
}

func (n nodeCredentialDo) Find() ([]*model.NodeCredential, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeCredential), err
}

func (n nodeCredentialDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeCredential, err error) {
	buf := make([]*model.NodeCredential, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeCredentialDo) FindInBatches(result *[]*model.NodeCredential, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeCredentialDo) Attrs(attrs ...field.AssignExpr) *nodeCredentialDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeCredentialDo) Assign(attrs ...field.AssignExpr) *nodeCredentialDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeCredentialDo) Joins(fields ...field.RelationField) *nodeCredentialDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeCredentialDo) Preload(fields ...field.RelationField) *nodeCredentialDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeCredentialDo) FirstOrInit() (*model.NodeCredential, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeCredential), nil
	}
}

func (n nodeCredentialDo) FirstOrCreate() (*model.NodeCredential, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeCredential), nil
	}
}

func (n nodeCredentialDo) FindByPage(offset int, limit int) (result []*model.NodeCredential, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeCredentialDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeCredentialDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeCredentialDo) Delete(models ...*model.NodeCredential) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeCredentialDo) withDO(do gen.Dao) *nodeCredentialDo {
	n.DO = *do.(*gen.DO)
	return n
}
