// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/0xJacky/Nginx-UI/model"
)

func newSiteHealthAlertState(db *gorm.DB, opts ...gen.DOOption) siteHealthAlertState {
	_siteHealthAlertState := siteHealthAlertState{}

	_siteHealthAlertState.siteHealthAlertStateDo.UseDB(db, opts...)
	_siteHealthAlertState.siteHealthAlertStateDo.UseModel(&model.SiteHealthAlertState{})

	tableName := _siteHealthAlertState.siteHealthAlertStateDo.TableName()
	_siteHealthAlertState.ALL = field.NewAsterisk(tableName)
	_siteHealthAlertState.ID = field.NewUint64(tableName, "id")
	_siteHealthAlertState.CreatedAt = field.NewTime(tableName, "created_at")
	_siteHealthAlertState.UpdatedAt = field.NewTime(tableName, "updated_at")
	_siteHealthAlertState.DeletedAt = field.NewField(tableName, "deleted_at")
	_siteHealthAlertState.SiteKey = field.NewString(tableName, "site_key")
	_siteHealthAlertState.LastStatus = field.NewString(tableName, "last_status")
	_siteHealthAlertState.ConsecutiveFailures = field.NewInt(tableName, "consecutive_failures")
	_siteHealthAlertState.FailureNotified = field.NewBool(tableName, "failure_notified")
	_siteHealthAlertState.LastNotifiedAt = field.NewTime(tableName, "last_notified_at")

	_siteHealthAlertState.fillFieldMap()

	return _siteHealthAlertState
}

type siteHealthAlertState struct {
	siteHealthAlertStateDo

	ALL                 field.Asterisk
	ID                  field.Uint64
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field
	SiteKey             field.String
	LastStatus          field.String
	ConsecutiveFailures field.Int
	FailureNotified     field.Bool
	LastNotifiedAt      field.Time

	fieldMap map[string]field.Expr
}

func (s siteHealthAlertState) Table(newTableName string) *siteHealthAlertState {
	s.siteHealthAlertStateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s siteHealthAlertState) As(alias string) *siteHealthAlertState {
	s.siteHealthAlertStateDo.DO = *(s.siteHealthAlertStateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *siteHealthAlertState) updateTableName(table string) *siteHealthAlertState {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.SiteKey = field.NewString(table, "site_key")
	s.LastStatus = field.NewString(table, "last_status")
	s.ConsecutiveFailures = field.NewInt(table, "consecutive_failures")
	s.FailureNotified = field.NewBool(table, "failure_notified")
	s.LastNotifiedAt = field.NewTime(table, "last_notified_at")

	s.fillFieldMap()

	return s
}

func (s *siteHealthAlertState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *siteHealthAlertState) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["site_key"] = s.SiteKey
	s.fieldMap["last_status"] = s.LastStatus
	s.fieldMap["consecutive_failures"] = s.ConsecutiveFailures
	s.fieldMap["failure_notified"] = s.FailureNotified
	s.fieldMap["last_notified_at"] = s.LastNotifiedAt
}

func (s siteHealthAlertState) clone(db *gorm.DB) siteHealthAlertState {
	s.siteHealthAlertStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s siteHealthAlertState) replaceDB(db *gorm.DB) siteHealthAlertState {
	s.siteHealthAlertStateDo.ReplaceDB(db)
	return s
}

type siteHealthAlertStateDo struct{ gen.DO }

// FirstByID Where("id=@id")
func (s siteHealthAlertStateDo) FirstByID(id uint64) (result *model.SiteHealthAlertState, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("id=? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Where(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DeleteByID update @@table set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=@id
func (s siteHealthAlertStateDo) DeleteByID(id uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("update site_health_alert_states set deleted_at=strftime('%Y-%m-%d %H:%M:%S','now') where id=? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (s siteHealthAlertStateDo) Debug() *siteHealthAlertStateDo {
	return s.withDO(s.DO.Debug())
}

func (s siteHealthAlertStateDo) WithContext(ctx context.Context) *siteHealthAlertStateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s siteHealthAlertStateDo) ReadDB() *siteHealthAlertStateDo {
	return s.Clauses(dbresolver.Read)
}

func (s siteHealthAlertStateDo) WriteDB() *siteHealthAlertStateDo {
	return s.Clauses(dbresolver.Write)
}

func (s siteHealthAlertStateDo) Session(config *gorm.Session) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Session(config))
}

func (s siteHealthAlertStateDo) Clauses(conds ...clause.Expression) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s siteHealthAlertStateDo) Returning(value interface{}, columns ...string) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s siteHealthAlertStateDo) Not(conds ...gen.Condition) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s siteHealthAlertStateDo) Or(conds ...gen.Condition) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s siteHealthAlertStateDo) Select(conds ...field.Expr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s siteHealthAlertStateDo) Where(conds ...gen.Condition) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s siteHealthAlertStateDo) Order(conds ...field.Expr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s siteHealthAlertStateDo) Distinct(cols ...field.Expr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s siteHealthAlertStateDo) Omit(cols ...field.Expr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s siteHealthAlertStateDo) Join(table schema.Tabler, on ...field.Expr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s siteHealthAlertStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s siteHealthAlertStateDo) RightJoin(table schema.Tabler, on ...field.Expr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s siteHealthAlertStateDo) Group(cols ...field.Expr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s siteHealthAlertStateDo) Having(conds ...gen.Condition) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s siteHealthAlertStateDo) Limit(limit int) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s siteHealthAlertStateDo) Offset(offset int) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s siteHealthAlertStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s siteHealthAlertStateDo) Unscoped() *siteHealthAlertStateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s siteHealthAlertStateDo) Create(values ...*model.SiteHealthAlertState) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s siteHealthAlertStateDo) CreateInBatches(values []*model.SiteHealthAlertState, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s siteHealthAlertStateDo) Save(values ...*model.SiteHealthAlertState) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s siteHealthAlertStateDo) First() (*model.SiteHealthAlertState, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SiteHealthAlertState), nil
	}
}

func (s siteHealthAlertStateDo) Take() (*model.SiteHealthAlertState, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SiteHealthAlertState), nil
	}
}

func (s siteHealthAlertStateDo) Last() (*model.SiteHealthAlertState, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SiteHealthAlertState), nil
	}
}

func (s siteHealthAlertStateDo) Find() ([]*model.SiteHealthAlertState, error) {
	result, err := s.DO.Find()
	return result.([]*model.SiteHealthAlertState), err
}

func (s siteHealthAlertStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SiteHealthAlertState, err error) {
	buf := make([]*model.SiteHealthAlertState, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s siteHealthAlertStateDo) FindInBatches(result *[]*model.SiteHealthAlertState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s siteHealthAlertStateDo) Attrs(attrs ...field.AssignExpr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s siteHealthAlertStateDo) Assign(attrs ...field.AssignExpr) *siteHealthAlertStateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s siteHealthAlertStateDo) Joins(fields ...field.RelationField) *siteHealthAlertStateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s siteHealthAlertStateDo) Preload(fields ...field.RelationField) *siteHealthAlertStateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s siteHealthAlertStateDo) FirstOrInit() (*model.SiteHealthAlertState, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SiteHealthAlertState), nil
	}
}

func (s siteHealthAlertStateDo) FirstOrCreate() (*model.SiteHealthAlertState, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SiteHealthAlertState), nil
	}
}

func (s siteHealthAlertStateDo) FindByPage(offset int, limit int) (result []*model.SiteHealthAlertState, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s siteHealthAlertStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s siteHealthAlertStateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s siteHealthAlertStateDo) Delete(models ...*model.SiteHealthAlertState) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *siteHealthAlertStateDo) withDO(do gen.Dao) *siteHealthAlertStateDo {
	s.DO = *do.(*gen.DO)
	return s
}
