// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nginxui/plugin/v1/deploy.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Deploy_Validate_FullMethodName = "/nginxui.plugin.v1.Deploy/Validate"
	Deploy_Push_FullMethodName     = "/nginxui.plugin.v1.Deploy/Push"
)

// DeployClient is the client API for Deploy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Deploy is the cert.deploy capability. A plugin that declares the capability
// pushes issued certificates to the kinds of external target its manifest
// lists (a CDN, a cloud load balancer, another server), and the host is the
// caller. See https://nginxui.com/plugin/capabilities/cert-deploy.
type DeployClient interface {
	// Validates a target configuration without contacting the target.
	// Optional.
	Validate(ctx context.Context, in *DeployValidateRequest, opts ...grpc.CallOption) (*DeployValidateResponse, error)
	// Pushes one certificate to one target.
	Push(ctx context.Context, in *DeployPushRequest, opts ...grpc.CallOption) (*DeployPushResponse, error)
}

type deployClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployClient(cc grpc.ClientConnInterface) DeployClient {
	return &deployClient{cc}
}

func (c *deployClient) Validate(ctx context.Context, in *DeployValidateRequest, opts ...grpc.CallOption) (*DeployValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployValidateResponse)
	err := c.cc.Invoke(ctx, Deploy_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployClient) Push(ctx context.Context, in *DeployPushRequest, opts ...grpc.CallOption) (*DeployPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployPushResponse)
	err := c.cc.Invoke(ctx, Deploy_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployServer is the server API for Deploy service.
// All implementations must embed UnimplementedDeployServer
// for forward compatibility.
//
// Deploy is the cert.deploy capability. A plugin that declares the capability
// pushes issued certificates to the kinds of external target its manifest
// lists (a CDN, a cloud load balancer, another server), and the host is the
// caller. See https://nginxui.com/plugin/capabilities/cert-deploy.
type DeployServer interface {
	// Validates a target configuration without contacting the target.
	// Optional.
	Validate(context.Context, *DeployValidateRequest) (*DeployValidateResponse, error)
	// Pushes one certificate to one target.
	Push(context.Context, *DeployPushRequest) (*DeployPushResponse, error)
	mustEmbedUnimplementedDeployServer()
}

// UnimplementedDeployServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployServer struct{}

func (UnimplementedDeployServer) Validate(context.Context, *DeployValidateRequest) (*DeployValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedDeployServer) Push(context.Context, *DeployPushRequest) (*DeployPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedDeployServer) mustEmbedUnimplementedDeployServer() {}
func (UnimplementedDeployServer) testEmbeddedByValue()                {}

// UnsafeDeployServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployServer will
// result in compilation errors.
type UnsafeDeployServer interface {
	mustEmbedUnimplementedDeployServer()
}

func RegisterDeployServer(s grpc.ServiceRegistrar, srv DeployServer) {
	// If the following call panics, it indicates UnimplementedDeployServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Deploy_ServiceDesc, srv)
}

func _Deploy_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploy_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).Validate(ctx, req.(*DeployValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploy_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploy_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).Push(ctx, req.(*DeployPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Deploy_ServiceDesc is the grpc.ServiceDesc for Deploy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deploy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nginxui.plugin.v1.Deploy",
	HandlerType: (*DeployServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _Deploy_Validate_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Deploy_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nginxui/plugin/v1/deploy.proto",
}
