// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nginxui/plugin/v1/discovery.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DiscoveryResolveRequest is the params of discovery.resolve.
type DiscoveryResolveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider code declared in the manifest, without any host prefix.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Field values the person filled in, keyed by field key.
	Config map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Name of the service to resolve, in the terms of the provider.
	Service       string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResolveRequest) Reset() {
	*x = DiscoveryResolveRequest{}
	mi := &file_nginxui_plugin_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResolveRequest) ProtoMessage() {}

func (x *DiscoveryResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResolveRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryResolveRequest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryResolveRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DiscoveryResolveRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DiscoveryResolveRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// DiscoveryResolveResponse is the result of discovery.resolve.
type DiscoveryResolveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every server that backs the service right now.
	Targets []*DiscoveryTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// How long the answer stays fresh, in seconds. 0 leaves the refresh
	// interval to the host.
	TtlSeconds    int32 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResolveResponse) Reset() {
	*x = DiscoveryResolveResponse{}
	mi := &file_nginxui_plugin_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResolveResponse) ProtoMessage() {}

func (x *DiscoveryResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResolveResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResolveResponse) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryResolveResponse) GetTargets() []*DiscoveryTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *DiscoveryResolveResponse) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// DiscoveryTarget is one server of a service.
type DiscoveryTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An IPv4 or IPv6 address or a host name, without a port.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// TCP port, 1 to 65535.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Relative weight of the server. 0 means 1.
	Weight int32 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	// Labels the provider attaches to the server, for display.
	Tags          []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryTarget) Reset() {
	*x = DiscoveryTarget{}
	mi := &file_nginxui_plugin_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryTarget) ProtoMessage() {}

func (x *DiscoveryTarget) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryTarget.ProtoReflect.Descriptor instead.
func (*DiscoveryTarget) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoveryTarget) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DiscoveryTarget) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DiscoveryTarget) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DiscoveryTarget) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_nginxui_plugin_v1_discovery_proto protoreflect.FileDescriptor

const file_nginxui_plugin_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"!nginxui/plugin/v1/discovery.proto\x12\x11nginxui.plugin.v1\x1a\x1fnginxui/plugin/v1/options.proto\"\xda\x01\n" +
	"\x17DiscoveryResolveRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12N\n" +
	"\x06config\x18\x02 \x03(\v26.nginxui.plugin.v1.DiscoveryResolveRequest.ConfigEntryR\x06config\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x18DiscoveryResolveResponse\x12<\n" +
	"\atargets\x18\x01 \x03(\v2\".nginxui.plugin.v1.DiscoveryTargetR\atargets\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x05R\n" +
	"ttlSeconds\"k\n" +
	"\x0fDiscoveryTarget\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags2\x86\x01\n" +
	"\tDiscovery\x12y\n" +
	"\aResolve\x12*.nginxui.plugin.v1.DiscoveryResolveRequest\x1a+.nginxui.plugin.v1.DiscoveryResolveResponse\"\x15\xaa\xb8\x19\x11discovery.resolveBBZ@github.com/nginxui/plugin-spec/gen/go/nginxui/plugin/v1;pluginv1b\x06proto3"

var (
	file_nginxui_plugin_v1_discovery_proto_rawDescOnce sync.Once
	file_nginxui_plugin_v1_discovery_proto_rawDescData []byte
)

func file_nginxui_plugin_v1_discovery_proto_rawDescGZIP() []byte {
	file_nginxui_plugin_v1_discovery_proto_rawDescOnce.Do(func() {
		file_nginxui_plugin_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_discovery_proto_rawDesc), len(file_nginxui_plugin_v1_discovery_proto_rawDesc)))
	})
	return file_nginxui_plugin_v1_discovery_proto_rawDescData
}

var file_nginxui_plugin_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nginxui_plugin_v1_discovery_proto_goTypes = []any{
	(*DiscoveryResolveRequest)(nil),  // 0: nginxui.plugin.v1.DiscoveryResolveRequest
	(*DiscoveryResolveResponse)(nil), // 1: nginxui.plugin.v1.DiscoveryResolveResponse
	(*DiscoveryTarget)(nil),          // 2: nginxui.plugin.v1.DiscoveryTarget
	nil,                              // 3: nginxui.plugin.v1.DiscoveryResolveRequest.ConfigEntry
}
var file_nginxui_plugin_v1_discovery_proto_depIdxs = []int32{
	3, // 0: nginxui.plugin.v1.DiscoveryResolveRequest.config:type_name -> nginxui.plugin.v1.DiscoveryResolveRequest.ConfigEntry
	2, // 1: nginxui.plugin.v1.DiscoveryResolveResponse.targets:type_name -> nginxui.plugin.v1.DiscoveryTarget
	0, // 2: nginxui.plugin.v1.Discovery.Resolve:input_type -> nginxui.plugin.v1.DiscoveryResolveRequest
	1, // 3: nginxui.plugin.v1.Discovery.Resolve:output_type -> nginxui.plugin.v1.DiscoveryResolveResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nginxui_plugin_v1_discovery_proto_init() }
func file_nginxui_plugin_v1_discovery_proto_init() {
	if File_nginxui_plugin_v1_discovery_proto != nil {
		return
	}
	file_nginxui_plugin_v1_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_discovery_proto_rawDesc), len(file_nginxui_plugin_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nginxui_plugin_v1_discovery_proto_goTypes,
		DependencyIndexes: file_nginxui_plugin_v1_discovery_proto_depIdxs,
		MessageInfos:      file_nginxui_plugin_v1_discovery_proto_msgTypes,
	}.Build()
	File_nginxui_plugin_v1_discovery_proto = out.File
	file_nginxui_plugin_v1_discovery_proto_goTypes = nil
	file_nginxui_plugin_v1_discovery_proto_depIdxs = nil
}
