// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nginxui/plugin/v1/dns01.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DNS01PresentRequest is the params of dns01.present.
type DNS01PresentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vendor code declared in the manifest, without the plugin id prefix.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Credential and additional fields the person filled in, merged.
	Config map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Per-certificate DNS-01 options produced by the plugin's challenge form
	// slot. Free-form JSON object, opaque to the host.
	Options *structpb.Struct `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	// Certificate identifier with any leading wildcard removed.
	Domain string `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	// The _acme-challenge name, without CNAME following.
	Fqdn string `protobuf:"bytes,5,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// CNAME target when known, otherwise equal to fqdn.
	EffectiveFqdn string `protobuf:"bytes,6,opt,name=effective_fqdn,json=effectiveFqdn,proto3" json:"effective_fqdn,omitempty"`
	// TXT record value derived from key_auth.
	Value string `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	// Raw ACME challenge token.
	Token string `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	// ACME key authorization. lego providers derive fqdn and value from it.
	KeyAuth string `protobuf:"bytes,9,opt,name=key_auth,json=keyAuth,proto3" json:"key_auth,omitempty"`
	// Validate shapes without touching the vendor API.
	DryRun        bool `protobuf:"varint,10,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01PresentRequest) Reset() {
	*x = DNS01PresentRequest{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01PresentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01PresentRequest) ProtoMessage() {}

func (x *DNS01PresentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01PresentRequest.ProtoReflect.Descriptor instead.
func (*DNS01PresentRequest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{0}
}

func (x *DNS01PresentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DNS01PresentRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DNS01PresentRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *DNS01PresentRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DNS01PresentRequest) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *DNS01PresentRequest) GetEffectiveFqdn() string {
	if x != nil {
		return x.EffectiveFqdn
	}
	return ""
}

func (x *DNS01PresentRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DNS01PresentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DNS01PresentRequest) GetKeyAuth() string {
	if x != nil {
		return x.KeyAuth
	}
	return ""
}

func (x *DNS01PresentRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// DNS01PresentResponse is the result of dns01.present. It is empty.
type DNS01PresentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01PresentResponse) Reset() {
	*x = DNS01PresentResponse{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01PresentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01PresentResponse) ProtoMessage() {}

func (x *DNS01PresentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01PresentResponse.ProtoReflect.Descriptor instead.
func (*DNS01PresentResponse) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{1}
}

// DNS01CleanupRequest is the params of dns01.cleanup. It has the same shape
// as DNS01PresentRequest.
type DNS01CleanupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vendor code declared in the manifest, without the plugin id prefix.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Credential and additional fields the person filled in, merged.
	Config map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Per-certificate DNS-01 options. Free-form JSON object.
	Options *structpb.Struct `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	// Certificate identifier with any leading wildcard removed.
	Domain string `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	// The _acme-challenge name, without CNAME following.
	Fqdn string `protobuf:"bytes,5,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// CNAME target when known, otherwise equal to fqdn.
	EffectiveFqdn string `protobuf:"bytes,6,opt,name=effective_fqdn,json=effectiveFqdn,proto3" json:"effective_fqdn,omitempty"`
	// TXT record value derived from key_auth.
	Value string `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	// Raw ACME challenge token.
	Token string `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	// ACME key authorization.
	KeyAuth string `protobuf:"bytes,9,opt,name=key_auth,json=keyAuth,proto3" json:"key_auth,omitempty"`
	// Validate shapes without touching the vendor API.
	DryRun        bool `protobuf:"varint,10,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01CleanupRequest) Reset() {
	*x = DNS01CleanupRequest{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01CleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01CleanupRequest) ProtoMessage() {}

func (x *DNS01CleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01CleanupRequest.ProtoReflect.Descriptor instead.
func (*DNS01CleanupRequest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{2}
}

func (x *DNS01CleanupRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DNS01CleanupRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DNS01CleanupRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *DNS01CleanupRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DNS01CleanupRequest) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *DNS01CleanupRequest) GetEffectiveFqdn() string {
	if x != nil {
		return x.EffectiveFqdn
	}
	return ""
}

func (x *DNS01CleanupRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DNS01CleanupRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DNS01CleanupRequest) GetKeyAuth() string {
	if x != nil {
		return x.KeyAuth
	}
	return ""
}

func (x *DNS01CleanupRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// DNS01CleanupResponse is the result of dns01.cleanup. It is empty.
type DNS01CleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01CleanupResponse) Reset() {
	*x = DNS01CleanupResponse{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01CleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01CleanupResponse) ProtoMessage() {}

func (x *DNS01CleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01CleanupResponse.ProtoReflect.Descriptor instead.
func (*DNS01CleanupResponse) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{3}
}

// DNS01OptionsRequest is the params of dns01.options.
type DNS01OptionsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Config   map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Per-certificate DNS-01 options. Free-form JSON object.
	Options       *structpb.Struct `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01OptionsRequest) Reset() {
	*x = DNS01OptionsRequest{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01OptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01OptionsRequest) ProtoMessage() {}

func (x *DNS01OptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01OptionsRequest.ProtoReflect.Descriptor instead.
func (*DNS01OptionsRequest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{4}
}

func (x *DNS01OptionsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DNS01OptionsRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DNS01OptionsRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

// DNS01OptionsResponse is the result of dns01.options.
type DNS01OptionsResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PropagationTimeoutSeconds int32                  `protobuf:"varint,1,opt,name=propagation_timeout_seconds,json=propagationTimeoutSeconds,proto3" json:"propagation_timeout_seconds,omitempty"`
	PollingIntervalSeconds    int32                  `protobuf:"varint,2,opt,name=polling_interval_seconds,json=pollingIntervalSeconds,proto3" json:"polling_interval_seconds,omitempty"`
	// Non-zero when the provider requires challenges to be solved one at a
	// time.
	SequentialIntervalSeconds int32 `protobuf:"varint,3,opt,name=sequential_interval_seconds,json=sequentialIntervalSeconds,proto3" json:"sequential_interval_seconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DNS01OptionsResponse) Reset() {
	*x = DNS01OptionsResponse{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01OptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01OptionsResponse) ProtoMessage() {}

func (x *DNS01OptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01OptionsResponse.ProtoReflect.Descriptor instead.
func (*DNS01OptionsResponse) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{5}
}

func (x *DNS01OptionsResponse) GetPropagationTimeoutSeconds() int32 {
	if x != nil {
		return x.PropagationTimeoutSeconds
	}
	return 0
}

func (x *DNS01OptionsResponse) GetPollingIntervalSeconds() int32 {
	if x != nil {
		return x.PollingIntervalSeconds
	}
	return 0
}

func (x *DNS01OptionsResponse) GetSequentialIntervalSeconds() int32 {
	if x != nil {
		return x.SequentialIntervalSeconds
	}
	return 0
}

// DNS01CheckRequest is the params of dns01.check.
type DNS01CheckRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Config   map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Per-certificate DNS-01 options. Free-form JSON object.
	Options       *structpb.Struct `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	Domain        string           `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Fqdn          string           `protobuf:"bytes,5,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Value         string           `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	KeyAuth       string           `protobuf:"bytes,7,opt,name=key_auth,json=keyAuth,proto3" json:"key_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01CheckRequest) Reset() {
	*x = DNS01CheckRequest{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01CheckRequest) ProtoMessage() {}

func (x *DNS01CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01CheckRequest.ProtoReflect.Descriptor instead.
func (*DNS01CheckRequest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{6}
}

func (x *DNS01CheckRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DNS01CheckRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DNS01CheckRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *DNS01CheckRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DNS01CheckRequest) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *DNS01CheckRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DNS01CheckRequest) GetKeyAuth() string {
	if x != nil {
		return x.KeyAuth
	}
	return ""
}

// DNS01CheckResponse is the result of dns01.check.
type DNS01CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ready bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// CNAME target the plugin resolved, when it differs from fqdn.
	EffectiveFqdn string `protobuf:"bytes,2,opt,name=effective_fqdn,json=effectiveFqdn,proto3" json:"effective_fqdn,omitempty"`
	// Human readable progress. The host copies it into the issuance log.
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01CheckResponse) Reset() {
	*x = DNS01CheckResponse{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01CheckResponse) ProtoMessage() {}

func (x *DNS01CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01CheckResponse.ProtoReflect.Descriptor instead.
func (*DNS01CheckResponse) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{7}
}

func (x *DNS01CheckResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *DNS01CheckResponse) GetEffectiveFqdn() string {
	if x != nil {
		return x.EffectiveFqdn
	}
	return ""
}

func (x *DNS01CheckResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// DNS01ValidateRequest is the params of dns01.validate.
type DNS01ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01ValidateRequest) Reset() {
	*x = DNS01ValidateRequest{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01ValidateRequest) ProtoMessage() {}

func (x *DNS01ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01ValidateRequest.ProtoReflect.Descriptor instead.
func (*DNS01ValidateRequest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{8}
}

func (x *DNS01ValidateRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DNS01ValidateRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// DNS01ValidateResponse is the result of dns01.validate. It is empty.
type DNS01ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01ValidateResponse) Reset() {
	*x = DNS01ValidateResponse{}
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01ValidateResponse) ProtoMessage() {}

func (x *DNS01ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_dns01_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01ValidateResponse.ProtoReflect.Descriptor instead.
func (*DNS01ValidateResponse) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_dns01_proto_rawDescGZIP(), []int{9}
}

var File_nginxui_plugin_v1_dns01_proto protoreflect.FileDescriptor

const file_nginxui_plugin_v1_dns01_proto_rawDesc = "" +
	"\n" +
	"\x1dnginxui/plugin/v1/dns01.proto\x12\x11nginxui.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fnginxui/plugin/v1/options.proto\"\x9e\x03\n" +
	"\x13DNS01PresentRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12J\n" +
	"\x06config\x18\x02 \x03(\v22.nginxui.plugin.v1.DNS01PresentRequest.ConfigEntryR\x06config\x121\n" +
	"\aoptions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\aoptions\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x12\n" +
	"\x04fqdn\x18\x05 \x01(\tR\x04fqdn\x12%\n" +
	"\x0eeffective_fqdn\x18\x06 \x01(\tR\reffectiveFqdn\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\x12\x19\n" +
	"\bkey_auth\x18\t \x01(\tR\akeyAuth\x12\x17\n" +
	"\adry_run\x18\n" +
	" \x01(\bR\x06dryRun\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14DNS01PresentResponse\"\x9e\x03\n" +
	"\x13DNS01CleanupRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12J\n" +
	"\x06config\x18\x02 \x03(\v22.nginxui.plugin.v1.DNS01CleanupRequest.ConfigEntryR\x06config\x121\n" +
	"\aoptions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\aoptions\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x12\n" +
	"\x04fqdn\x18\x05 \x01(\tR\x04fqdn\x12%\n" +
	"\x0eeffective_fqdn\x18\x06 \x01(\tR\reffectiveFqdn\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\x12\x19\n" +
	"\bkey_auth\x18\t \x01(\tR\akeyAuth\x12\x17\n" +
	"\adry_run\x18\n" +
	" \x01(\bR\x06dryRun\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14DNS01CleanupResponse\"\xeb\x01\n" +
	"\x13DNS01OptionsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12J\n" +
	"\x06config\x18\x02 \x03(\v22.nginxui.plugin.v1.DNS01OptionsRequest.ConfigEntryR\x06config\x121\n" +
	"\aoptions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\aoptions\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x14DNS01OptionsResponse\x12>\n" +
	"\x1bpropagation_timeout_seconds\x18\x01 \x01(\x05R\x19propagationTimeoutSeconds\x128\n" +
	"\x18polling_interval_seconds\x18\x02 \x01(\x05R\x16pollingIntervalSeconds\x12>\n" +
	"\x1bsequential_interval_seconds\x18\x03 \x01(\x05R\x19sequentialIntervalSeconds\"\xc4\x02\n" +
	"\x11DNS01CheckRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12H\n" +
	"\x06config\x18\x02 \x03(\v20.nginxui.plugin.v1.DNS01CheckRequest.ConfigEntryR\x06config\x121\n" +
	"\aoptions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\aoptions\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x12\n" +
	"\x04fqdn\x18\x05 \x01(\tR\x04fqdn\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12\x19\n" +
	"\bkey_auth\x18\a \x01(\tR\akeyAuth\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x12DNS01CheckResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12%\n" +
	"\x0eeffective_fqdn\x18\x02 \x01(\tR\reffectiveFqdn\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xba\x01\n" +
	"\x14DNS01ValidateRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12K\n" +
	"\x06config\x18\x02 \x03(\v23.nginxui.plugin.v1.DNS01ValidateRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15DNS01ValidateResponse2\xae\x04\n" +
	"\x05DNS01\x12m\n" +
	"\aPresent\x12&.nginxui.plugin.v1.DNS01PresentRequest\x1a'.nginxui.plugin.v1.DNS01PresentResponse\"\x11\xaa\xb8\x19\rdns01.present\x12m\n" +
	"\aCleanup\x12&.nginxui.plugin.v1.DNS01CleanupRequest\x1a'.nginxui.plugin.v1.DNS01CleanupResponse\"\x11\xaa\xb8\x19\rdns01.cleanup\x12m\n" +
	"\aOptions\x12&.nginxui.plugin.v1.DNS01OptionsRequest\x1a'.nginxui.plugin.v1.DNS01OptionsResponse\"\x11\xaa\xb8\x19\rdns01.options\x12e\n" +
	"\x05Check\x12$.nginxui.plugin.v1.DNS01CheckRequest\x1a%.nginxui.plugin.v1.DNS01CheckResponse\"\x0f\xaa\xb8\x19\vdns01.check\x12q\n" +
	"\bValidate\x12'.nginxui.plugin.v1.DNS01ValidateRequest\x1a(.nginxui.plugin.v1.DNS01ValidateResponse\"\x12\xaa\xb8\x19\x0edns01.validateBKZIgithub.com/0xJacky/nginx-ui-plugin-spec/gen/go/nginxui/plugin/v1;pluginv1b\x06proto3"

var (
	file_nginxui_plugin_v1_dns01_proto_rawDescOnce sync.Once
	file_nginxui_plugin_v1_dns01_proto_rawDescData []byte
)

func file_nginxui_plugin_v1_dns01_proto_rawDescGZIP() []byte {
	file_nginxui_plugin_v1_dns01_proto_rawDescOnce.Do(func() {
		file_nginxui_plugin_v1_dns01_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_dns01_proto_rawDesc), len(file_nginxui_plugin_v1_dns01_proto_rawDesc)))
	})
	return file_nginxui_plugin_v1_dns01_proto_rawDescData
}

var file_nginxui_plugin_v1_dns01_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_nginxui_plugin_v1_dns01_proto_goTypes = []any{
	(*DNS01PresentRequest)(nil),   // 0: nginxui.plugin.v1.DNS01PresentRequest
	(*DNS01PresentResponse)(nil),  // 1: nginxui.plugin.v1.DNS01PresentResponse
	(*DNS01CleanupRequest)(nil),   // 2: nginxui.plugin.v1.DNS01CleanupRequest
	(*DNS01CleanupResponse)(nil),  // 3: nginxui.plugin.v1.DNS01CleanupResponse
	(*DNS01OptionsRequest)(nil),   // 4: nginxui.plugin.v1.DNS01OptionsRequest
	(*DNS01OptionsResponse)(nil),  // 5: nginxui.plugin.v1.DNS01OptionsResponse
	(*DNS01CheckRequest)(nil),     // 6: nginxui.plugin.v1.DNS01CheckRequest
	(*DNS01CheckResponse)(nil),    // 7: nginxui.plugin.v1.DNS01CheckResponse
	(*DNS01ValidateRequest)(nil),  // 8: nginxui.plugin.v1.DNS01ValidateRequest
	(*DNS01ValidateResponse)(nil), // 9: nginxui.plugin.v1.DNS01ValidateResponse
	nil,                           // 10: nginxui.plugin.v1.DNS01PresentRequest.ConfigEntry
	nil,                           // 11: nginxui.plugin.v1.DNS01CleanupRequest.ConfigEntry
	nil,                           // 12: nginxui.plugin.v1.DNS01OptionsRequest.ConfigEntry
	nil,                           // 13: nginxui.plugin.v1.DNS01CheckRequest.ConfigEntry
	nil,                           // 14: nginxui.plugin.v1.DNS01ValidateRequest.ConfigEntry
	(*structpb.Struct)(nil),       // 15: google.protobuf.Struct
}
var file_nginxui_plugin_v1_dns01_proto_depIdxs = []int32{
	10, // 0: nginxui.plugin.v1.DNS01PresentRequest.config:type_name -> nginxui.plugin.v1.DNS01PresentRequest.ConfigEntry
	15, // 1: nginxui.plugin.v1.DNS01PresentRequest.options:type_name -> google.protobuf.Struct
	11, // 2: nginxui.plugin.v1.DNS01CleanupRequest.config:type_name -> nginxui.plugin.v1.DNS01CleanupRequest.ConfigEntry
	15, // 3: nginxui.plugin.v1.DNS01CleanupRequest.options:type_name -> google.protobuf.Struct
	12, // 4: nginxui.plugin.v1.DNS01OptionsRequest.config:type_name -> nginxui.plugin.v1.DNS01OptionsRequest.ConfigEntry
	15, // 5: nginxui.plugin.v1.DNS01OptionsRequest.options:type_name -> google.protobuf.Struct
	13, // 6: nginxui.plugin.v1.DNS01CheckRequest.config:type_name -> nginxui.plugin.v1.DNS01CheckRequest.ConfigEntry
	15, // 7: nginxui.plugin.v1.DNS01CheckRequest.options:type_name -> google.protobuf.Struct
	14, // 8: nginxui.plugin.v1.DNS01ValidateRequest.config:type_name -> nginxui.plugin.v1.DNS01ValidateRequest.ConfigEntry
	0,  // 9: nginxui.plugin.v1.DNS01.Present:input_type -> nginxui.plugin.v1.DNS01PresentRequest
	2,  // 10: nginxui.plugin.v1.DNS01.Cleanup:input_type -> nginxui.plugin.v1.DNS01CleanupRequest
	4,  // 11: nginxui.plugin.v1.DNS01.Options:input_type -> nginxui.plugin.v1.DNS01OptionsRequest
	6,  // 12: nginxui.plugin.v1.DNS01.Check:input_type -> nginxui.plugin.v1.DNS01CheckRequest
	8,  // 13: nginxui.plugin.v1.DNS01.Validate:input_type -> nginxui.plugin.v1.DNS01ValidateRequest
	1,  // 14: nginxui.plugin.v1.DNS01.Present:output_type -> nginxui.plugin.v1.DNS01PresentResponse
	3,  // 15: nginxui.plugin.v1.DNS01.Cleanup:output_type -> nginxui.plugin.v1.DNS01CleanupResponse
	5,  // 16: nginxui.plugin.v1.DNS01.Options:output_type -> nginxui.plugin.v1.DNS01OptionsResponse
	7,  // 17: nginxui.plugin.v1.DNS01.Check:output_type -> nginxui.plugin.v1.DNS01CheckResponse
	9,  // 18: nginxui.plugin.v1.DNS01.Validate:output_type -> nginxui.plugin.v1.DNS01ValidateResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nginxui_plugin_v1_dns01_proto_init() }
func file_nginxui_plugin_v1_dns01_proto_init() {
	if File_nginxui_plugin_v1_dns01_proto != nil {
		return
	}
	file_nginxui_plugin_v1_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_dns01_proto_rawDesc), len(file_nginxui_plugin_v1_dns01_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nginxui_plugin_v1_dns01_proto_goTypes,
		DependencyIndexes: file_nginxui_plugin_v1_dns01_proto_depIdxs,
		MessageInfos:      file_nginxui_plugin_v1_dns01_proto_msgTypes,
	}.Build()
	File_nginxui_plugin_v1_dns01_proto = out.File
	file_nginxui_plugin_v1_dns01_proto_goTypes = nil
	file_nginxui_plugin_v1_dns01_proto_depIdxs = nil
}
