// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nginxui/plugin/v1/events.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventsOnRequest is the params of events.on. A fired cron entry reuses this
// shape as the params of a request to the entry's own method, with type set
// to the entry id and no data.
type EventsOnRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type such as "cert.renewed".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Event payload. Any JSON value, absent for a cron invocation.
	Data *structpb.Value `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Unix seconds when the host sent the event. uint32 instead of int32 so the
	// value does not overflow in 2038 while the JSON stays a number.
	Ts            uint32 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsOnRequest) Reset() {
	*x = EventsOnRequest{}
	mi := &file_nginxui_plugin_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsOnRequest) ProtoMessage() {}

func (x *EventsOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsOnRequest.ProtoReflect.Descriptor instead.
func (*EventsOnRequest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventsOnRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventsOnRequest) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EventsOnRequest) GetTs() uint32 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// EventsOnResponse is never sent on stdio; events.on is a notification.
type EventsOnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsOnResponse) Reset() {
	*x = EventsOnResponse{}
	mi := &file_nginxui_plugin_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsOnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsOnResponse) ProtoMessage() {}

func (x *EventsOnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsOnResponse.ProtoReflect.Descriptor instead.
func (*EventsOnResponse) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_events_proto_rawDescGZIP(), []int{1}
}

var File_nginxui_plugin_v1_events_proto protoreflect.FileDescriptor

const file_nginxui_plugin_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1enginxui/plugin/v1/events.proto\x12\x11nginxui.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fnginxui/plugin/v1/options.proto\"a\n" +
	"\x0fEventsOnRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x04data\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\rR\x02ts\"\x12\n" +
	"\x10EventsOnResponse2j\n" +
	"\x06Events\x12`\n" +
	"\x02On\x12\".nginxui.plugin.v1.EventsOnRequest\x1a#.nginxui.plugin.v1.EventsOnResponse\"\x11\xaa\xb8\x19\tevents.on\xb0\xb8\x19\x01BBZ@github.com/nginxui/plugin-spec/gen/go/nginxui/plugin/v1;pluginv1b\x06proto3"

var (
	file_nginxui_plugin_v1_events_proto_rawDescOnce sync.Once
	file_nginxui_plugin_v1_events_proto_rawDescData []byte
)

func file_nginxui_plugin_v1_events_proto_rawDescGZIP() []byte {
	file_nginxui_plugin_v1_events_proto_rawDescOnce.Do(func() {
		file_nginxui_plugin_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_events_proto_rawDesc), len(file_nginxui_plugin_v1_events_proto_rawDesc)))
	})
	return file_nginxui_plugin_v1_events_proto_rawDescData
}

var file_nginxui_plugin_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nginxui_plugin_v1_events_proto_goTypes = []any{
	(*EventsOnRequest)(nil),  // 0: nginxui.plugin.v1.EventsOnRequest
	(*EventsOnResponse)(nil), // 1: nginxui.plugin.v1.EventsOnResponse
	(*structpb.Value)(nil),   // 2: google.protobuf.Value
}
var file_nginxui_plugin_v1_events_proto_depIdxs = []int32{
	2, // 0: nginxui.plugin.v1.EventsOnRequest.data:type_name -> google.protobuf.Value
	0, // 1: nginxui.plugin.v1.Events.On:input_type -> nginxui.plugin.v1.EventsOnRequest
	1, // 2: nginxui.plugin.v1.Events.On:output_type -> nginxui.plugin.v1.EventsOnResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nginxui_plugin_v1_events_proto_init() }
func file_nginxui_plugin_v1_events_proto_init() {
	if File_nginxui_plugin_v1_events_proto != nil {
		return
	}
	file_nginxui_plugin_v1_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_events_proto_rawDesc), len(file_nginxui_plugin_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nginxui_plugin_v1_events_proto_goTypes,
		DependencyIndexes: file_nginxui_plugin_v1_events_proto_depIdxs,
		MessageInfos:      file_nginxui_plugin_v1_events_proto_msgTypes,
	}.Build()
	File_nginxui_plugin_v1_events_proto = out.File
	file_nginxui_plugin_v1_events_proto_goTypes = nil
	file_nginxui_plugin_v1_events_proto_depIdxs = nil
}
