// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nginxui/plugin/v1/host.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Host_Log_FullMethodName             = "/nginxui.plugin.v1.Host/Log"
	Host_KVGet_FullMethodName           = "/nginxui.plugin.v1.Host/KVGet"
	Host_KVSet_FullMethodName           = "/nginxui.plugin.v1.Host/KVSet"
	Host_KVDelete_FullMethodName        = "/nginxui.plugin.v1.Host/KVDelete"
	Host_KVList_FullMethodName          = "/nginxui.plugin.v1.Host/KVList"
	Host_SettingsGet_FullMethodName     = "/nginxui.plugin.v1.Host/SettingsGet"
	Host_I18NLocale_FullMethodName      = "/nginxui.plugin.v1.Host/I18nLocale"
	Host_CredentialsGet_FullMethodName  = "/nginxui.plugin.v1.Host/CredentialsGet"
	Host_CronRegister_FullMethodName    = "/nginxui.plugin.v1.Host/CronRegister"
	Host_CronUnregister_FullMethodName  = "/nginxui.plugin.v1.Host/CronUnregister"
	Host_Notify_FullMethodName          = "/nginxui.plugin.v1.Host/Notify"
	Host_MetricsSnapshot_FullMethodName = "/nginxui.plugin.v1.Host/MetricsSnapshot"
)

// HostClient is the client API for Host service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Host is the API the host serves to its plugins. The plugin is the caller,
// and only after plugin.initialized. Each method needs the permission listed
// in spec/06-host-api.md; without it the host replies
// ERROR_CODE_PERMISSION_DENIED.
type HostClient interface {
	// Writes a structured log line into the host logger. A caller MAY send it
	// as a notification when it does not need the reply.
	Log(ctx context.Context, in *HostLogRequest, opts ...grpc.CallOption) (*HostLogResponse, error)
	// Reads one key of the plugin's private key-value store. Permission "kv".
	KVGet(ctx context.Context, in *HostKVGetRequest, opts ...grpc.CallOption) (*HostKVGetResponse, error)
	// Writes one key. Permission "kv".
	KVSet(ctx context.Context, in *HostKVSetRequest, opts ...grpc.CallOption) (*HostKVSetResponse, error)
	// Deletes one key. Permission "kv".
	KVDelete(ctx context.Context, in *HostKVDeleteRequest, opts ...grpc.CallOption) (*HostKVDeleteResponse, error)
	// Lists keys by prefix. Permission "kv".
	KVList(ctx context.Context, in *HostKVListRequest, opts ...grpc.CallOption) (*HostKVListResponse, error)
	// Reads the plugin's own current settings values.
	SettingsGet(ctx context.Context, in *HostSettingsGetRequest, opts ...grpc.CallOption) (*HostSettingsGetResponse, error)
	// Reads the host's current UI locale.
	I18NLocale(ctx context.Context, in *HostI18NLocaleRequest, opts ...grpc.CallOption) (*HostI18NLocaleResponse, error)
	// Reads one stored credential. Permission "credentials.read:<kind>".
	CredentialsGet(ctx context.Context, in *HostCredentialsGetRequest, opts ...grpc.CallOption) (*HostCredentialsGetResponse, error)
	// Registers a cron entry at runtime. Permission "cron".
	CronRegister(ctx context.Context, in *HostCronRegisterRequest, opts ...grpc.CallOption) (*HostCronRegisterResponse, error)
	// Removes a cron entry registered earlier. Permission "cron".
	CronUnregister(ctx context.Context, in *HostCronUnregisterRequest, opts ...grpc.CallOption) (*HostCronUnregisterResponse, error)
	// Creates a notification in the host UI. Permission "notify".
	Notify(ctx context.Context, in *HostNotifyRequest, opts ...grpc.CallOption) (*HostNotifyResponse, error)
	// Reads the host's current metrics snapshot. Permission "metrics.read".
	MetricsSnapshot(ctx context.Context, in *HostMetricsSnapshotRequest, opts ...grpc.CallOption) (*HostMetricsSnapshotResponse, error)
}

type hostClient struct {
	cc grpc.ClientConnInterface
}

func NewHostClient(cc grpc.ClientConnInterface) HostClient {
	return &hostClient{cc}
}

func (c *hostClient) Log(ctx context.Context, in *HostLogRequest, opts ...grpc.CallOption) (*HostLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostLogResponse)
	err := c.cc.Invoke(ctx, Host_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) KVGet(ctx context.Context, in *HostKVGetRequest, opts ...grpc.CallOption) (*HostKVGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostKVGetResponse)
	err := c.cc.Invoke(ctx, Host_KVGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) KVSet(ctx context.Context, in *HostKVSetRequest, opts ...grpc.CallOption) (*HostKVSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostKVSetResponse)
	err := c.cc.Invoke(ctx, Host_KVSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) KVDelete(ctx context.Context, in *HostKVDeleteRequest, opts ...grpc.CallOption) (*HostKVDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostKVDeleteResponse)
	err := c.cc.Invoke(ctx, Host_KVDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) KVList(ctx context.Context, in *HostKVListRequest, opts ...grpc.CallOption) (*HostKVListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostKVListResponse)
	err := c.cc.Invoke(ctx, Host_KVList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) SettingsGet(ctx context.Context, in *HostSettingsGetRequest, opts ...grpc.CallOption) (*HostSettingsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostSettingsGetResponse)
	err := c.cc.Invoke(ctx, Host_SettingsGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) I18NLocale(ctx context.Context, in *HostI18NLocaleRequest, opts ...grpc.CallOption) (*HostI18NLocaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostI18NLocaleResponse)
	err := c.cc.Invoke(ctx, Host_I18NLocale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) CredentialsGet(ctx context.Context, in *HostCredentialsGetRequest, opts ...grpc.CallOption) (*HostCredentialsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostCredentialsGetResponse)
	err := c.cc.Invoke(ctx, Host_CredentialsGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) CronRegister(ctx context.Context, in *HostCronRegisterRequest, opts ...grpc.CallOption) (*HostCronRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostCronRegisterResponse)
	err := c.cc.Invoke(ctx, Host_CronRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) CronUnregister(ctx context.Context, in *HostCronUnregisterRequest, opts ...grpc.CallOption) (*HostCronUnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostCronUnregisterResponse)
	err := c.cc.Invoke(ctx, Host_CronUnregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) Notify(ctx context.Context, in *HostNotifyRequest, opts ...grpc.CallOption) (*HostNotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostNotifyResponse)
	err := c.cc.Invoke(ctx, Host_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) MetricsSnapshot(ctx context.Context, in *HostMetricsSnapshotRequest, opts ...grpc.CallOption) (*HostMetricsSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostMetricsSnapshotResponse)
	err := c.cc.Invoke(ctx, Host_MetricsSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServer is the server API for Host service.
// All implementations must embed UnimplementedHostServer
// for forward compatibility.
//
// Host is the API the host serves to its plugins. The plugin is the caller,
// and only after plugin.initialized. Each method needs the permission listed
// in spec/06-host-api.md; without it the host replies
// ERROR_CODE_PERMISSION_DENIED.
type HostServer interface {
	// Writes a structured log line into the host logger. A caller MAY send it
	// as a notification when it does not need the reply.
	Log(context.Context, *HostLogRequest) (*HostLogResponse, error)
	// Reads one key of the plugin's private key-value store. Permission "kv".
	KVGet(context.Context, *HostKVGetRequest) (*HostKVGetResponse, error)
	// Writes one key. Permission "kv".
	KVSet(context.Context, *HostKVSetRequest) (*HostKVSetResponse, error)
	// Deletes one key. Permission "kv".
	KVDelete(context.Context, *HostKVDeleteRequest) (*HostKVDeleteResponse, error)
	// Lists keys by prefix. Permission "kv".
	KVList(context.Context, *HostKVListRequest) (*HostKVListResponse, error)
	// Reads the plugin's own current settings values.
	SettingsGet(context.Context, *HostSettingsGetRequest) (*HostSettingsGetResponse, error)
	// Reads the host's current UI locale.
	I18NLocale(context.Context, *HostI18NLocaleRequest) (*HostI18NLocaleResponse, error)
	// Reads one stored credential. Permission "credentials.read:<kind>".
	CredentialsGet(context.Context, *HostCredentialsGetRequest) (*HostCredentialsGetResponse, error)
	// Registers a cron entry at runtime. Permission "cron".
	CronRegister(context.Context, *HostCronRegisterRequest) (*HostCronRegisterResponse, error)
	// Removes a cron entry registered earlier. Permission "cron".
	CronUnregister(context.Context, *HostCronUnregisterRequest) (*HostCronUnregisterResponse, error)
	// Creates a notification in the host UI. Permission "notify".
	Notify(context.Context, *HostNotifyRequest) (*HostNotifyResponse, error)
	// Reads the host's current metrics snapshot. Permission "metrics.read".
	MetricsSnapshot(context.Context, *HostMetricsSnapshotRequest) (*HostMetricsSnapshotResponse, error)
	mustEmbedUnimplementedHostServer()
}

// UnimplementedHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServer struct{}

func (UnimplementedHostServer) Log(context.Context, *HostLogRequest) (*HostLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServer) KVGet(context.Context, *HostKVGetRequest) (*HostKVGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVGet not implemented")
}
func (UnimplementedHostServer) KVSet(context.Context, *HostKVSetRequest) (*HostKVSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVSet not implemented")
}
func (UnimplementedHostServer) KVDelete(context.Context, *HostKVDeleteRequest) (*HostKVDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVDelete not implemented")
}
func (UnimplementedHostServer) KVList(context.Context, *HostKVListRequest) (*HostKVListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVList not implemented")
}
func (UnimplementedHostServer) SettingsGet(context.Context, *HostSettingsGetRequest) (*HostSettingsGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettingsGet not implemented")
}
func (UnimplementedHostServer) I18NLocale(context.Context, *HostI18NLocaleRequest) (*HostI18NLocaleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method I18NLocale not implemented")
}
func (UnimplementedHostServer) CredentialsGet(context.Context, *HostCredentialsGetRequest) (*HostCredentialsGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CredentialsGet not implemented")
}
func (UnimplementedHostServer) CronRegister(context.Context, *HostCronRegisterRequest) (*HostCronRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronRegister not implemented")
}
func (UnimplementedHostServer) CronUnregister(context.Context, *HostCronUnregisterRequest) (*HostCronUnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronUnregister not implemented")
}
func (UnimplementedHostServer) Notify(context.Context, *HostNotifyRequest) (*HostNotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedHostServer) MetricsSnapshot(context.Context, *HostMetricsSnapshotRequest) (*HostMetricsSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MetricsSnapshot not implemented")
}
func (UnimplementedHostServer) mustEmbedUnimplementedHostServer() {}
func (UnimplementedHostServer) testEmbeddedByValue()              {}

// UnsafeHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServer will
// result in compilation errors.
type UnsafeHostServer interface {
	mustEmbedUnimplementedHostServer()
}

func RegisterHostServer(s grpc.ServiceRegistrar, srv HostServer) {
	// If the following call panics, it indicates UnimplementedHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Host_ServiceDesc, srv)
}

func _Host_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).Log(ctx, req.(*HostLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_KVGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostKVGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).KVGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_KVGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).KVGet(ctx, req.(*HostKVGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_KVSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostKVSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).KVSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_KVSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).KVSet(ctx, req.(*HostKVSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_KVDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostKVDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).KVDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_KVDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).KVDelete(ctx, req.(*HostKVDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_KVList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostKVListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).KVList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_KVList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).KVList(ctx, req.(*HostKVListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_SettingsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostSettingsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).SettingsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_SettingsGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).SettingsGet(ctx, req.(*HostSettingsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_I18NLocale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostI18NLocaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).I18NLocale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_I18NLocale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).I18NLocale(ctx, req.(*HostI18NLocaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_CredentialsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostCredentialsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).CredentialsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_CredentialsGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).CredentialsGet(ctx, req.(*HostCredentialsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_CronRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostCronRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).CronRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_CronRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).CronRegister(ctx, req.(*HostCronRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_CronUnregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostCronUnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).CronUnregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_CronUnregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).CronUnregister(ctx, req.(*HostCronUnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).Notify(ctx, req.(*HostNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_MetricsSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostMetricsSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).MetricsSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_MetricsSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).MetricsSnapshot(ctx, req.(*HostMetricsSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Host_ServiceDesc is the grpc.ServiceDesc for Host service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Host_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nginxui.plugin.v1.Host",
	HandlerType: (*HostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _Host_Log_Handler,
		},
		{
			MethodName: "KVGet",
			Handler:    _Host_KVGet_Handler,
		},
		{
			MethodName: "KVSet",
			Handler:    _Host_KVSet_Handler,
		},
		{
			MethodName: "KVDelete",
			Handler:    _Host_KVDelete_Handler,
		},
		{
			MethodName: "KVList",
			Handler:    _Host_KVList_Handler,
		},
		{
			MethodName: "SettingsGet",
			Handler:    _Host_SettingsGet_Handler,
		},
		{
			MethodName: "I18nLocale",
			Handler:    _Host_I18NLocale_Handler,
		},
		{
			MethodName: "CredentialsGet",
			Handler:    _Host_CredentialsGet_Handler,
		},
		{
			MethodName: "CronRegister",
			Handler:    _Host_CronRegister_Handler,
		},
		{
			MethodName: "CronUnregister",
			Handler:    _Host_CronUnregister_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Host_Notify_Handler,
		},
		{
			MethodName: "MetricsSnapshot",
			Handler:    _Host_MetricsSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nginxui/plugin/v1/host.proto",
}
