// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nginxui/plugin/v1/manifest.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manifest is plugin.json, see spec/01-manifest.md. Its protobuf JSON mapping
// with proto field names is the file format. schema/plugin.schema.json adds
// the validation rules on top and is checked against this message.
type Manifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reverse domain plugin id, e.g. "com.nginxui.dns01".
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Semantic version of the plugin.
	Version     string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	HomepageUrl string `protobuf:"bytes,5,opt,name=homepage_url,json=homepageUrl,proto3" json:"homepage_url,omitempty"`
	// Package relative path of the icon.
	IconPath string `protobuf:"bytes,6,opt,name=icon_path,json=iconPath,proto3" json:"icon_path,omitempty"`
	// Protocol major version the plugin targets.
	ApiVersion int32 `protobuf:"varint,7,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Lowest host version the plugin supports.
	MinNginxUiVersion string `protobuf:"bytes,8,opt,name=min_nginx_ui_version,json=minNginxUiVersion,proto3" json:"min_nginx_ui_version,omitempty"`
	// How to start the plugin process. Absent for process-less plugins.
	Server *ManifestServer `protobuf:"bytes,9,opt,name=server,proto3" json:"server,omitempty"`
	// Optional browser bundle.
	Webapp *ManifestWebapp `protobuf:"bytes,10,opt,name=webapp,proto3" json:"webapp,omitempty"`
	// Process-less contributions.
	Content *ManifestContent `protobuf:"bytes,11,opt,name=content,proto3" json:"content,omitempty"`
	// Capabilities the plugin implements, e.g. "dns01".
	Capabilities []string `protobuf:"bytes,12,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Permissions the plugin requests, e.g. "kv" or "credentials.read:dns".
	Permissions []string `protobuf:"bytes,13,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Hard dependencies on other plugins.
	Requires []*ManifestRequirement `protobuf:"bytes,14,rep,name=requires,proto3" json:"requires,omitempty"`
	// Capabilities some installed plugin must provide.
	RequiresCapabilities []string `protobuf:"bytes,15,rep,name=requires_capabilities,json=requiresCapabilities,proto3" json:"requires_capabilities,omitempty"`
	// Event types delivered through events.on.
	Events []string `protobuf:"bytes,16,rep,name=events,proto3" json:"events,omitempty"`
	// Host scheduled tasks.
	Cron []*ManifestCron `protobuf:"bytes,17,rep,name=cron,proto3" json:"cron,omitempty"`
	// Hosts the plugin talks to, shown to the person before install.
	NetworkHosts []string `protobuf:"bytes,18,rep,name=network_hosts,json=networkHosts,proto3" json:"network_hosts,omitempty"`
	// Metadata of the dns01 capability.
	Dns01 *ManifestDNS01 `protobuf:"bytes,19,opt,name=dns01,proto3" json:"dns01,omitempty"`
	// Metadata of the http capability.
	Http *ManifestHTTP `protobuf:"bytes,20,opt,name=http,proto3" json:"http,omitempty"`
	// Drives the auto-rendered settings form.
	SettingsSchema *SettingsSchema `protobuf:"bytes,21,opt,name=settings_schema,json=settingsSchema,proto3" json:"settings_schema,omitempty"`
	// Metadata of the notify capability.
	Notify *ManifestNotify `protobuf:"bytes,22,opt,name=notify,proto3" json:"notify,omitempty"`
	// Metadata of the probe capability.
	Probe *ManifestProbe `protobuf:"bytes,23,opt,name=probe,proto3" json:"probe,omitempty"`
	// Metadata of the mcp capability.
	Mcp *ManifestMCP `protobuf:"bytes,24,opt,name=mcp,proto3" json:"mcp,omitempty"`
	// Metadata of the storage capability.
	Storage *ManifestStorage `protobuf:"bytes,25,opt,name=storage,proto3" json:"storage,omitempty"`
	// Metadata of the cert.deploy capability.
	Deploy *ManifestDeploy `protobuf:"bytes,26,opt,name=deploy,proto3" json:"deploy,omitempty"`
	// Metadata of the security.blocklist capability.
	Blocklist *ManifestBlocklist `protobuf:"bytes,27,opt,name=blocklist,proto3" json:"blocklist,omitempty"`
	// Metadata of the upstream.discovery capability.
	Discovery *ManifestDiscovery `protobuf:"bytes,28,opt,name=discovery,proto3" json:"discovery,omitempty"`
	// Tuning of the log.sink capability.
	LogSink *ManifestLogSink `protobuf:"bytes,29,opt,name=log_sink,json=logSink,proto3" json:"log_sink,omitempty"`
	// Translations of name and description keyed by host locale code, e.g.
	// "zh_CN". name and description stay the fallback.
	I18N          map[string]*ManifestI18N `protobuf:"bytes,30,rep,name=i18n,proto3" json:"i18n,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest) GetHomepageUrl() string {
	if x != nil {
		return x.HomepageUrl
	}
	return ""
}

func (x *Manifest) GetIconPath() string {
	if x != nil {
		return x.IconPath
	}
	return ""
}

func (x *Manifest) GetApiVersion() int32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Manifest) GetMinNginxUiVersion() string {
	if x != nil {
		return x.MinNginxUiVersion
	}
	return ""
}

func (x *Manifest) GetServer() *ManifestServer {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Manifest) GetWebapp() *ManifestWebapp {
	if x != nil {
		return x.Webapp
	}
	return nil
}

func (x *Manifest) GetContent() *ManifestContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Manifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Manifest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Manifest) GetRequires() []*ManifestRequirement {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *Manifest) GetRequiresCapabilities() []string {
	if x != nil {
		return x.RequiresCapabilities
	}
	return nil
}

func (x *Manifest) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Manifest) GetCron() []*ManifestCron {
	if x != nil {
		return x.Cron
	}
	return nil
}

func (x *Manifest) GetNetworkHosts() []string {
	if x != nil {
		return x.NetworkHosts
	}
	return nil
}

func (x *Manifest) GetDns01() *ManifestDNS01 {
	if x != nil {
		return x.Dns01
	}
	return nil
}

func (x *Manifest) GetHttp() *ManifestHTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Manifest) GetSettingsSchema() *SettingsSchema {
	if x != nil {
		return x.SettingsSchema
	}
	return nil
}

func (x *Manifest) GetNotify() *ManifestNotify {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *Manifest) GetProbe() *ManifestProbe {
	if x != nil {
		return x.Probe
	}
	return nil
}

func (x *Manifest) GetMcp() *ManifestMCP {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *Manifest) GetStorage() *ManifestStorage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Manifest) GetDeploy() *ManifestDeploy {
	if x != nil {
		return x.Deploy
	}
	return nil
}

func (x *Manifest) GetBlocklist() *ManifestBlocklist {
	if x != nil {
		return x.Blocklist
	}
	return nil
}

func (x *Manifest) GetDiscovery() *ManifestDiscovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *Manifest) GetLogSink() *ManifestLogSink {
	if x != nil {
		return x.LogSink
	}
	return nil
}

func (x *Manifest) GetI18N() map[string]*ManifestI18N {
	if x != nil {
		return x.I18N
	}
	return nil
}

// ManifestI18n translates the display fields of a manifest into one
// language. An empty string means no translation for that field.
type ManifestI18N struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestI18N) Reset() {
	*x = ManifestI18N{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestI18N) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestI18N) ProtoMessage() {}

func (x *ManifestI18N) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestI18N.ProtoReflect.Descriptor instead.
func (*ManifestI18N) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestI18N) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManifestI18N) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ManifestServer describes how to start the plugin process.
type ManifestServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maps "<goos>-<goarch>" to a package relative executable path.
	Executables map[string]string `protobuf:"bytes,1,rep,name=executables,proto3" json:"executables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Fallback argv for interpreted plugins.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// "resident" (default) or "on_demand".
	Lifecycle string `protobuf:"bytes,3,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	// Idle time after which an on_demand process is stopped.
	IdleTimeoutSeconds int32 `protobuf:"varint,4,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	// Resource hints of the process, applied by a host that confines plugin
	// processes and capped by its own limits.
	Resources     *ManifestResources `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestServer) Reset() {
	*x = ManifestServer{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestServer) ProtoMessage() {}

func (x *ManifestServer) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestServer.ProtoReflect.Descriptor instead.
func (*ManifestServer) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *ManifestServer) GetExecutables() map[string]string {
	if x != nil {
		return x.Executables
	}
	return nil
}

func (x *ManifestServer) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ManifestServer) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

func (x *ManifestServer) GetIdleTimeoutSeconds() int32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *ManifestServer) GetResources() *ManifestResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

// ManifestResources are the resources a plugin process needs at most. A host
// that confines plugin processes applies the smaller of a hint and its own
// limit; a hint never raises a limit. See spec/04-lifecycle.md LIFE-16.
type ManifestResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Memory in MiB. 0 means no hint.
	MemoryMb int32 `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	// CPU time in percent of one core, 100 being one core. 0 means no hint.
	CpuPercent    int32 `protobuf:"varint,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResources) Reset() {
	*x = ManifestResources{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResources) ProtoMessage() {}

func (x *ManifestResources) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResources.ProtoReflect.Descriptor instead.
func (*ManifestResources) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *ManifestResources) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ManifestResources) GetCpuPercent() int32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

// ManifestWebapp describes the optional browser bundle.
type ManifestWebapp struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BundlePath string                 `protobuf:"bytes,1,opt,name=bundle_path,json=bundlePath,proto3" json:"bundle_path,omitempty"`
	StylePath  string                 `protobuf:"bytes,2,opt,name=style_path,json=stylePath,proto3" json:"style_path,omitempty"`
	// Maps a shared runtime library to the semver range the bundle was built
	// against.
	Shared map[string]string `protobuf:"bytes,3,rep,name=shared,proto3" json:"shared,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Zero-build iframe pages.
	Pages         []*ManifestPage `protobuf:"bytes,4,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestWebapp) Reset() {
	*x = ManifestWebapp{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestWebapp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestWebapp) ProtoMessage() {}

func (x *ManifestWebapp) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestWebapp.ProtoReflect.Descriptor instead.
func (*ManifestWebapp) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *ManifestWebapp) GetBundlePath() string {
	if x != nil {
		return x.BundlePath
	}
	return ""
}

func (x *ManifestWebapp) GetStylePath() string {
	if x != nil {
		return x.StylePath
	}
	return ""
}

func (x *ManifestWebapp) GetShared() map[string]string {
	if x != nil {
		return x.Shared
	}
	return nil
}

func (x *ManifestWebapp) GetPages() []*ManifestPage {
	if x != nil {
		return x.Pages
	}
	return nil
}

// ManifestPage is a zero-build iframe page.
type ManifestPage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Page title keyed by locale.
	Title map[string]string `protobuf:"bytes,2,rep,name=title,proto3" json:"title,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Icon  string            `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	// Package relative HTML file.
	File          string `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestPage) Reset() {
	*x = ManifestPage{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestPage) ProtoMessage() {}

func (x *ManifestPage) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestPage.ProtoReflect.Descriptor instead.
func (*ManifestPage) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *ManifestPage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ManifestPage) GetTitle() map[string]string {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *ManifestPage) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ManifestPage) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// ManifestContent declares process-less contributions. See
// spec/17-content-plugins.md.
type ManifestContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package relative directory holding conf/ and block/ config templates.
	Templates string `protobuf:"bytes,1,opt,name=templates,proto3" json:"templates,omitempty"`
	// Package relative directory holding <lang>.po translation files.
	Locales       string `protobuf:"bytes,2,opt,name=locales,proto3" json:"locales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestContent) Reset() {
	*x = ManifestContent{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestContent) ProtoMessage() {}

func (x *ManifestContent) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestContent.ProtoReflect.Descriptor instead.
func (*ManifestContent) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{6}
}

func (x *ManifestContent) GetTemplates() string {
	if x != nil {
		return x.Templates
	}
	return ""
}

func (x *ManifestContent) GetLocales() string {
	if x != nil {
		return x.Locales
	}
	return ""
}

// ManifestRequirement is a hard dependency on another plugin.
type ManifestRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Semver range. Empty accepts any version.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequirement) Reset() {
	*x = ManifestRequirement{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequirement) ProtoMessage() {}

func (x *ManifestRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequirement.ProtoReflect.Descriptor instead.
func (*ManifestRequirement) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{7}
}

func (x *ManifestRequirement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManifestRequirement) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ManifestCron is a host scheduled task.
type ManifestCron struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Five-field cron expression or "@every <duration>".
	Schedule string `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// Plugin method the host invokes when the schedule fires.
	Method        string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestCron) Reset() {
	*x = ManifestCron{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestCron) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestCron) ProtoMessage() {}

func (x *ManifestCron) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestCron.ProtoReflect.Descriptor instead.
func (*ManifestCron) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{8}
}

func (x *ManifestCron) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManifestCron) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *ManifestCron) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// ManifestDNS01 is the metadata block of the dns01 capability.
type ManifestDNS01 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*DNS01Provider       `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestDNS01) Reset() {
	*x = ManifestDNS01{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestDNS01) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestDNS01) ProtoMessage() {}

func (x *ManifestDNS01) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestDNS01.ProtoReflect.Descriptor instead.
func (*ManifestDNS01) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{9}
}

func (x *ManifestDNS01) GetProviders() []*DNS01Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// DNS01Provider describes one vendor a plugin can solve DNS-01 for.
type DNS01Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Vendor code, shared across every installed dns01 plugin.
	Code  string              `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Links *DNS01ProviderLinks `protobuf:"bytes,4,opt,name=links,proto3" json:"links,omitempty"`
	// Default used when the plugin does not implement dns01.options.
	PropagationTimeoutSeconds int32 `protobuf:"varint,5,opt,name=propagation_timeout_seconds,json=propagationTimeoutSeconds,proto3" json:"propagation_timeout_seconds,omitempty"`
	// Default used when the plugin does not implement dns01.options.
	PollingIntervalSeconds int32 `protobuf:"varint,6,opt,name=polling_interval_seconds,json=pollingIntervalSeconds,proto3" json:"polling_interval_seconds,omitempty"`
	// Credential form, see DNS01-14. Required.
	Form          *DNS01ProviderForm `protobuf:"bytes,7,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01Provider) Reset() {
	*x = DNS01Provider{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01Provider) ProtoMessage() {}

func (x *DNS01Provider) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01Provider.ProtoReflect.Descriptor instead.
func (*DNS01Provider) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{10}
}

func (x *DNS01Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNS01Provider) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DNS01Provider) GetLinks() *DNS01ProviderLinks {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *DNS01Provider) GetPropagationTimeoutSeconds() int32 {
	if x != nil {
		return x.PropagationTimeoutSeconds
	}
	return 0
}

func (x *DNS01Provider) GetPollingIntervalSeconds() int32 {
	if x != nil {
		return x.PollingIntervalSeconds
	}
	return 0
}

func (x *DNS01Provider) GetForm() *DNS01ProviderForm {
	if x != nil {
		return x.Form
	}
	return nil
}

// DNS01ProviderLinks points at vendor documentation.
type DNS01ProviderLinks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Api           string                 `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01ProviderLinks) Reset() {
	*x = DNS01ProviderLinks{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01ProviderLinks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01ProviderLinks) ProtoMessage() {}

func (x *DNS01ProviderLinks) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01ProviderLinks.ProtoReflect.Descriptor instead.
func (*DNS01ProviderLinks) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{11}
}

func (x *DNS01ProviderLinks) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

// DNS01ProviderForm describes how a host lays out the credential form.
type DNS01ProviderForm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields in display order.
	Fields []*DNS01ProviderField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// Ways to sign in, present only when there is more than one.
	Methods       []*DNS01ProviderMethod `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01ProviderForm) Reset() {
	*x = DNS01ProviderForm{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01ProviderForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01ProviderForm) ProtoMessage() {}

func (x *DNS01ProviderForm) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01ProviderForm.ProtoReflect.Descriptor instead.
func (*DNS01ProviderForm) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{12}
}

func (x *DNS01ProviderForm) GetFields() []*DNS01ProviderField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DNS01ProviderForm) GetMethods() []*DNS01ProviderMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

// DNS01ProviderField is one input of the credential form.
type DNS01ProviderField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config key the value is stored and sent under.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Short plain English label, a gettext msgid.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Optional plain English sentence, a gettext msgid.
	Help string `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	// "credential" or "setting".
	Group    string `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Optional bool   `protobuf:"varint,5,opt,name=optional,proto3" json:"optional,omitempty"`
	// Rendered as a password input.
	Secret bool `protobuf:"varint,6,opt,name=secret,proto3" json:"secret,omitempty"`
	// Value used when the field is left empty, shown as a placeholder.
	Default string `protobuf:"bytes,7,opt,name=default,proto3" json:"default,omitempty"`
	// "seconds" or empty.
	Unit string `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	// Documentation URL for the field.
	Link          string `protobuf:"bytes,9,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01ProviderField) Reset() {
	*x = DNS01ProviderField{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01ProviderField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01ProviderField) ProtoMessage() {}

func (x *DNS01ProviderField) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01ProviderField.ProtoReflect.Descriptor instead.
func (*DNS01ProviderField) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{13}
}

func (x *DNS01ProviderField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DNS01ProviderField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DNS01ProviderField) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *DNS01ProviderField) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DNS01ProviderField) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *DNS01ProviderField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *DNS01ProviderField) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *DNS01ProviderField) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *DNS01ProviderField) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

// DNS01ProviderMethod is one way to sign in to the vendor.
type DNS01ProviderMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plain English name, a gettext msgid.
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Recommended bool   `protobuf:"varint,2,opt,name=recommended,proto3" json:"recommended,omitempty"`
	// Credential field keys this method uses. May be empty.
	Fields []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Fixed config values the host stores while this method is chosen.
	Values        map[string]string `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNS01ProviderMethod) Reset() {
	*x = DNS01ProviderMethod{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNS01ProviderMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS01ProviderMethod) ProtoMessage() {}

func (x *DNS01ProviderMethod) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS01ProviderMethod.ProtoReflect.Descriptor instead.
func (*DNS01ProviderMethod) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{14}
}

func (x *DNS01ProviderMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNS01ProviderMethod) GetRecommended() bool {
	if x != nil {
		return x.Recommended
	}
	return false
}

func (x *DNS01ProviderMethod) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DNS01ProviderMethod) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

// ManifestHTTP is the metadata block of the http capability.
type ManifestHTTP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "unix" (reverse proxy to a socket) or "rpc" (http.handle fallback).
	Listen        string `protobuf:"bytes,1,opt,name=listen,proto3" json:"listen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestHTTP) Reset() {
	*x = ManifestHTTP{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestHTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestHTTP) ProtoMessage() {}

func (x *ManifestHTTP) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestHTTP.ProtoReflect.Descriptor instead.
func (*ManifestHTTP) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{15}
}

func (x *ManifestHTTP) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

// ManifestNotify is the metadata block of the notify capability.
type ManifestNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*NotifyChannel       `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestNotify) Reset() {
	*x = ManifestNotify{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestNotify) ProtoMessage() {}

func (x *ManifestNotify) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestNotify.ProtoReflect.Descriptor instead.
func (*ManifestNotify) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{16}
}

func (x *ManifestNotify) GetChannels() []*NotifyChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

// NotifyChannel describes one vendor channel a plugin delivers notifications
// through.
type NotifyChannel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel code, shared across every installed notify plugin.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Fields of the channel form.
	Configuration *ConfigurationSchema `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyChannel) Reset() {
	*x = NotifyChannel{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyChannel) ProtoMessage() {}

func (x *NotifyChannel) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyChannel.ProtoReflect.Descriptor instead.
func (*NotifyChannel) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{17}
}

func (x *NotifyChannel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NotifyChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyChannel) GetConfiguration() *ConfigurationSchema {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// ManifestProbe is the metadata block of the probe capability.
type ManifestProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []*ProbeKind           `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestProbe) Reset() {
	*x = ManifestProbe{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestProbe) ProtoMessage() {}

func (x *ManifestProbe) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestProbe.ProtoReflect.Descriptor instead.
func (*ManifestProbe) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{18}
}

func (x *ManifestProbe) GetKinds() []*ProbeKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// ProbeKind describes one way a plugin can check the health of a target.
type ProbeKind struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind code, shared across every installed probe plugin.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Fields of the probe form.
	Configuration *ConfigurationSchema `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeKind) Reset() {
	*x = ProbeKind{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeKind) ProtoMessage() {}

func (x *ProbeKind) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeKind.ProtoReflect.Descriptor instead.
func (*ProbeKind) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{19}
}

func (x *ProbeKind) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProbeKind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProbeKind) GetConfiguration() *ConfigurationSchema {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// ManifestStorage is the metadata block of the storage capability.
type ManifestStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*StorageBackend      `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestStorage) Reset() {
	*x = ManifestStorage{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestStorage) ProtoMessage() {}

func (x *ManifestStorage) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestStorage.ProtoReflect.Descriptor instead.
func (*ManifestStorage) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{20}
}

func (x *ManifestStorage) GetBackends() []*StorageBackend {
	if x != nil {
		return x.Backends
	}
	return nil
}

// StorageBackend describes one place a plugin can keep host files.
type StorageBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend code, shared across every installed storage plugin.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Fields of the backend form.
	Configuration *ConfigurationSchema `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackend) Reset() {
	*x = StorageBackend{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackend) ProtoMessage() {}

func (x *StorageBackend) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBackend.ProtoReflect.Descriptor instead.
func (*StorageBackend) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{21}
}

func (x *StorageBackend) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StorageBackend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageBackend) GetConfiguration() *ConfigurationSchema {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// ManifestDeploy is the metadata block of the cert.deploy capability.
type ManifestDeploy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*DeployTarget        `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestDeploy) Reset() {
	*x = ManifestDeploy{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestDeploy) ProtoMessage() {}

func (x *ManifestDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestDeploy.ProtoReflect.Descriptor instead.
func (*ManifestDeploy) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{22}
}

func (x *ManifestDeploy) GetTargets() []*DeployTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

// DeployTarget describes one kind of external target a plugin can push
// certificates to.
type DeployTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target kind code, shared across every installed cert.deploy plugin.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Fields of the target form.
	Configuration *ConfigurationSchema `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployTarget) Reset() {
	*x = DeployTarget{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployTarget) ProtoMessage() {}

func (x *DeployTarget) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployTarget.ProtoReflect.Descriptor instead.
func (*DeployTarget) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{23}
}

func (x *DeployTarget) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeployTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployTarget) GetConfiguration() *ConfigurationSchema {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// ManifestBlocklist is the metadata block of the security.blocklist
// capability.
type ManifestBlocklist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*BlocklistSource     `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestBlocklist) Reset() {
	*x = ManifestBlocklist{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestBlocklist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestBlocklist) ProtoMessage() {}

func (x *ManifestBlocklist) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestBlocklist.ProtoReflect.Descriptor instead.
func (*ManifestBlocklist) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{24}
}

func (x *ManifestBlocklist) GetSources() []*BlocklistSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

// BlocklistSource describes one kind of source a plugin can fetch a list of
// addresses to deny from.
type BlocklistSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source kind code, shared across every installed security.blocklist
	// plugin.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Fields of the source form.
	Configuration *ConfigurationSchema `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// Default refresh interval of a source of this kind. 0 means 3600, a
	// value below 60 is invalid.
	RefreshSeconds int32 `protobuf:"varint,4,opt,name=refresh_seconds,json=refreshSeconds,proto3" json:"refresh_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlocklistSource) Reset() {
	*x = BlocklistSource{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocklistSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocklistSource) ProtoMessage() {}

func (x *BlocklistSource) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocklistSource.ProtoReflect.Descriptor instead.
func (*BlocklistSource) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{25}
}

func (x *BlocklistSource) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BlocklistSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlocklistSource) GetConfiguration() *ConfigurationSchema {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *BlocklistSource) GetRefreshSeconds() int32 {
	if x != nil {
		return x.RefreshSeconds
	}
	return 0
}

// ManifestDiscovery is the metadata block of the upstream.discovery
// capability.
type ManifestDiscovery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*DiscoveryProvider   `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestDiscovery) Reset() {
	*x = ManifestDiscovery{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestDiscovery) ProtoMessage() {}

func (x *ManifestDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestDiscovery.ProtoReflect.Descriptor instead.
func (*ManifestDiscovery) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{26}
}

func (x *ManifestDiscovery) GetProviders() []*DiscoveryProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// DiscoveryProvider describes one place a plugin can resolve services from.
type DiscoveryProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider code, shared across every installed upstream.discovery plugin.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Fields of the provider form.
	Configuration *ConfigurationSchema `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryProvider) Reset() {
	*x = DiscoveryProvider{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryProvider) ProtoMessage() {}

func (x *DiscoveryProvider) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryProvider.ProtoReflect.Descriptor instead.
func (*DiscoveryProvider) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{27}
}

func (x *DiscoveryProvider) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DiscoveryProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiscoveryProvider) GetConfiguration() *ConfigurationSchema {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// ManifestLogSink tunes the log.sink capability. Every field is optional.
type ManifestLogSink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Most entries the host sends in one log.push stream. 0 means 256, at most
	// 4096.
	BatchSize int32 `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// Longest time in milliseconds the host keeps a log.push stream open once
	// its first entry was sent. 0 means 500, at least 50.
	FlushIntervalMs int32 `protobuf:"varint,2,opt,name=flush_interval_ms,json=flushIntervalMs,proto3" json:"flush_interval_ms,omitempty"`
	// Formats of the lines the plugin wants, "combined" or "raw". Empty means
	// every line.
	Formats       []string `protobuf:"bytes,3,rep,name=formats,proto3" json:"formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestLogSink) Reset() {
	*x = ManifestLogSink{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestLogSink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestLogSink) ProtoMessage() {}

func (x *ManifestLogSink) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestLogSink.ProtoReflect.Descriptor instead.
func (*ManifestLogSink) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{28}
}

func (x *ManifestLogSink) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ManifestLogSink) GetFlushIntervalMs() int32 {
	if x != nil {
		return x.FlushIntervalMs
	}
	return 0
}

func (x *ManifestLogSink) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

// ConfigurationSchema drives the form of a notify channel, a probe kind, a
// storage backend, a deploy target, a blocklist source or a discovery
// provider. The values travel as a map of strings.
type ConfigurationSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ConfigurationField  `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationSchema) Reset() {
	*x = ConfigurationSchema{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSchema) ProtoMessage() {}

func (x *ConfigurationSchema) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSchema.ProtoReflect.Descriptor instead.
func (*ConfigurationSchema) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{29}
}

func (x *ConfigurationSchema) GetFields() []*ConfigurationField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ConfigurationField is one entry of ConfigurationSchema.
type ConfigurationField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key of the value in the config map.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// One of "text" (default), "textarea", "number", "bool".
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	HelpText    string `protobuf:"bytes,4,opt,name=help_text,json=helpText,proto3" json:"help_text,omitempty"`
	Required    bool   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	// The value is a credential: masked in forms and never logged.
	Secret        bool `protobuf:"varint,6,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationField) Reset() {
	*x = ConfigurationField{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationField) ProtoMessage() {}

func (x *ConfigurationField) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationField.ProtoReflect.Descriptor instead.
func (*ConfigurationField) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{30}
}

func (x *ConfigurationField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigurationField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigurationField) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ConfigurationField) GetHelpText() string {
	if x != nil {
		return x.HelpText
	}
	return ""
}

func (x *ConfigurationField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigurationField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

// ManifestMCP is the metadata block of the mcp capability.
type ManifestMCP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*MCPTool             `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestMCP) Reset() {
	*x = ManifestMCP{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestMCP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestMCP) ProtoMessage() {}

func (x *ManifestMCP) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestMCP.ProtoReflect.Descriptor instead.
func (*ManifestMCP) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{31}
}

func (x *ManifestMCP) GetTools() []*MCPTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

// MCPTool describes one Model Context Protocol tool a plugin serves.
type MCPTool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name, unique within the plugin. The host publishes it with a prefix
	// derived from the plugin id.
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema of the arguments object. Absent means no arguments.
	InputSchema   *structpb.Struct `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPTool) Reset() {
	*x = MCPTool{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPTool) ProtoMessage() {}

func (x *MCPTool) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPTool.ProtoReflect.Descriptor instead.
func (*MCPTool) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{32}
}

func (x *MCPTool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPTool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPTool) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

// SettingsSchema drives the auto-rendered settings form.
type SettingsSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Footer        string                 `protobuf:"bytes,2,opt,name=footer,proto3" json:"footer,omitempty"`
	Settings      []*SettingsField       `protobuf:"bytes,3,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsSchema) Reset() {
	*x = SettingsSchema{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsSchema) ProtoMessage() {}

func (x *SettingsSchema) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsSchema.ProtoReflect.Descriptor instead.
func (*SettingsSchema) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{33}
}

func (x *SettingsSchema) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SettingsSchema) GetFooter() string {
	if x != nil {
		return x.Footer
	}
	return ""
}

func (x *SettingsSchema) GetSettings() []*SettingsField {
	if x != nil {
		return x.Settings
	}
	return nil
}

// SettingsField is one entry of SettingsSchema.
type SettingsField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// One of "text", "bool", "number", "select", "secret", "textarea".
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	HelpText    string `protobuf:"bytes,4,opt,name=help_text,json=helpText,proto3" json:"help_text,omitempty"`
	// Default value. Any JSON value matching type.
	Default *structpb.Value `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	// Choices of a select field.
	Options       []*SettingsOption `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	Required      bool              `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsField) Reset() {
	*x = SettingsField{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsField) ProtoMessage() {}

func (x *SettingsField) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsField.ProtoReflect.Descriptor instead.
func (*SettingsField) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{34}
}

func (x *SettingsField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SettingsField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SettingsField) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SettingsField) GetHelpText() string {
	if x != nil {
		return x.HelpText
	}
	return ""
}

func (x *SettingsField) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *SettingsField) GetOptions() []*SettingsOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SettingsField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// SettingsOption is a choice of a select field.
type SettingsOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsOption) Reset() {
	*x = SettingsOption{}
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsOption) ProtoMessage() {}

func (x *SettingsOption) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_manifest_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsOption.ProtoReflect.Descriptor instead.
func (*SettingsOption) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_manifest_proto_rawDescGZIP(), []int{35}
}

func (x *SettingsOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SettingsOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_nginxui_plugin_v1_manifest_proto protoreflect.FileDescriptor

const file_nginxui_plugin_v1_manifest_proto_rawDesc = "" +
	"\n" +
	" nginxui/plugin/v1/manifest.proto\x12\x11nginxui.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x94\f\n" +
	"\bManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fhomepage_url\x18\x05 \x01(\tR\vhomepageUrl\x12\x1b\n" +
	"\ticon_path\x18\x06 \x01(\tR\biconPath\x12\x1f\n" +
	"\vapi_version\x18\a \x01(\x05R\n" +
	"apiVersion\x12/\n" +
	"\x14min_nginx_ui_version\x18\b \x01(\tR\x11minNginxUiVersion\x129\n" +
	"\x06server\x18\t \x01(\v2!.nginxui.plugin.v1.ManifestServerR\x06server\x129\n" +
	"\x06webapp\x18\n" +
	" \x01(\v2!.nginxui.plugin.v1.ManifestWebappR\x06webapp\x12<\n" +
	"\acontent\x18\v \x01(\v2\".nginxui.plugin.v1.ManifestContentR\acontent\x12\"\n" +
	"\fcapabilities\x18\f \x03(\tR\fcapabilities\x12 \n" +
	"\vpermissions\x18\r \x03(\tR\vpermissions\x12B\n" +
	"\brequires\x18\x0e \x03(\v2&.nginxui.plugin.v1.ManifestRequirementR\brequires\x123\n" +
	"\x15requires_capabilities\x18\x0f \x03(\tR\x14requiresCapabilities\x12\x16\n" +
	"\x06events\x18\x10 \x03(\tR\x06events\x123\n" +
	"\x04cron\x18\x11 \x03(\v2\x1f.nginxui.plugin.v1.ManifestCronR\x04cron\x12#\n" +
	"\rnetwork_hosts\x18\x12 \x03(\tR\fnetworkHosts\x126\n" +
	"\x05dns01\x18\x13 \x01(\v2 .nginxui.plugin.v1.ManifestDNS01R\x05dns01\x123\n" +
	"\x04http\x18\x14 \x01(\v2\x1f.nginxui.plugin.v1.ManifestHTTPR\x04http\x12J\n" +
	"\x0fsettings_schema\x18\x15 \x01(\v2!.nginxui.plugin.v1.SettingsSchemaR\x0esettingsSchema\x129\n" +
	"\x06notify\x18\x16 \x01(\v2!.nginxui.plugin.v1.ManifestNotifyR\x06notify\x126\n" +
	"\x05probe\x18\x17 \x01(\v2 .nginxui.plugin.v1.ManifestProbeR\x05probe\x120\n" +
	"\x03mcp\x18\x18 \x01(\v2\x1e.nginxui.plugin.v1.ManifestMCPR\x03mcp\x12<\n" +
	"\astorage\x18\x19 \x01(\v2\".nginxui.plugin.v1.ManifestStorageR\astorage\x129\n" +
	"\x06deploy\x18\x1a \x01(\v2!.nginxui.plugin.v1.ManifestDeployR\x06deploy\x12B\n" +
	"\tblocklist\x18\x1b \x01(\v2$.nginxui.plugin.v1.ManifestBlocklistR\tblocklist\x12B\n" +
	"\tdiscovery\x18\x1c \x01(\v2$.nginxui.plugin.v1.ManifestDiscoveryR\tdiscovery\x12=\n" +
	"\blog_sink\x18\x1d \x01(\v2\".nginxui.plugin.v1.ManifestLogSinkR\alogSink\x129\n" +
	"\x04i18n\x18\x1e \x03(\v2%.nginxui.plugin.v1.Manifest.I18nEntryR\x04i18n\x1aX\n" +
	"\tI18nEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.nginxui.plugin.v1.ManifestI18nR\x05value:\x028\x01\"D\n" +
	"\fManifestI18n\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xd4\x02\n" +
	"\x0eManifestServer\x12T\n" +
	"\vexecutables\x18\x01 \x03(\v22.nginxui.plugin.v1.ManifestServer.ExecutablesEntryR\vexecutables\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x1c\n" +
	"\tlifecycle\x18\x03 \x01(\tR\tlifecycle\x120\n" +
	"\x14idle_timeout_seconds\x18\x04 \x01(\x05R\x12idleTimeoutSeconds\x12B\n" +
	"\tresources\x18\x05 \x01(\v2$.nginxui.plugin.v1.ManifestResourcesR\tresources\x1a>\n" +
	"\x10ExecutablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x11ManifestResources\x12\x1b\n" +
	"\tmemory_mb\x18\x01 \x01(\x05R\bmemoryMb\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x05R\n" +
	"cpuPercent\"\x89\x02\n" +
	"\x0eManifestWebapp\x12\x1f\n" +
	"\vbundle_path\x18\x01 \x01(\tR\n" +
	"bundlePath\x12\x1d\n" +
	"\n" +
	"style_path\x18\x02 \x01(\tR\tstylePath\x12E\n" +
	"\x06shared\x18\x03 \x03(\v2-.nginxui.plugin.v1.ManifestWebapp.SharedEntryR\x06shared\x125\n" +
	"\x05pages\x18\x04 \x03(\v2\x1f.nginxui.plugin.v1.ManifestPageR\x05pages\x1a9\n" +
	"\vSharedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\fManifestPage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12@\n" +
	"\x05title\x18\x02 \x03(\v2*.nginxui.plugin.v1.ManifestPage.TitleEntryR\x05title\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x1a8\n" +
	"\n" +
	"TitleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x0fManifestContent\x12\x1c\n" +
	"\ttemplates\x18\x01 \x01(\tR\ttemplates\x12\x18\n" +
	"\alocales\x18\x02 \x01(\tR\alocales\"?\n" +
	"\x13ManifestRequirement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"R\n" +
	"\fManifestCron\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bschedule\x18\x02 \x01(\tR\bschedule\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"O\n" +
	"\rManifestDNS01\x12>\n" +
	"\tproviders\x18\x01 \x03(\v2 .nginxui.plugin.v1.DNS01ProviderR\tproviders\"\xbd\x02\n" +
	"\rDNS01Provider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12;\n" +
	"\x05links\x18\x04 \x01(\v2%.nginxui.plugin.v1.DNS01ProviderLinksR\x05links\x12>\n" +
	"\x1bpropagation_timeout_seconds\x18\x05 \x01(\x05R\x19propagationTimeoutSeconds\x128\n" +
	"\x18polling_interval_seconds\x18\x06 \x01(\x05R\x16pollingIntervalSeconds\x128\n" +
	"\x04form\x18\a \x01(\v2$.nginxui.plugin.v1.DNS01ProviderFormR\x04formJ\x04\b\x03\x10\x04R\rconfiguration\"7\n" +
	"\x12DNS01ProviderLinks\x12\x10\n" +
	"\x03api\x18\x01 \x01(\tR\x03apiJ\x04\b\x02\x10\x03R\tgo_client\"\x94\x01\n" +
	"\x11DNS01ProviderForm\x12=\n" +
	"\x06fields\x18\x01 \x03(\v2%.nginxui.plugin.v1.DNS01ProviderFieldR\x06fields\x12@\n" +
	"\amethods\x18\x02 \x03(\v2&.nginxui.plugin.v1.DNS01ProviderMethodR\amethods\"\xdc\x01\n" +
	"\x12DNS01ProviderField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04help\x18\x03 \x01(\tR\x04help\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x1a\n" +
	"\boptional\x18\x05 \x01(\bR\boptional\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\bR\x06secret\x12\x18\n" +
	"\adefault\x18\a \x01(\tR\adefault\x12\x12\n" +
	"\x04unit\x18\b \x01(\tR\x04unit\x12\x12\n" +
	"\x04link\x18\t \x01(\tR\x04link\"\xea\x01\n" +
	"\x13DNS01ProviderMethod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vrecommended\x18\x02 \x01(\bR\vrecommended\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12J\n" +
	"\x06values\x18\x04 \x03(\v22.nginxui.plugin.v1.DNS01ProviderMethod.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\fManifestHTTP\x12\x16\n" +
	"\x06listen\x18\x01 \x01(\tR\x06listen\"N\n" +
	"\x0eManifestNotify\x12<\n" +
	"\bchannels\x18\x01 \x03(\v2 .nginxui.plugin.v1.NotifyChannelR\bchannels\"\x85\x01\n" +
	"\rNotifyChannel\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12L\n" +
	"\rconfiguration\x18\x03 \x01(\v2&.nginxui.plugin.v1.ConfigurationSchemaR\rconfiguration\"C\n" +
	"\rManifestProbe\x122\n" +
	"\x05kinds\x18\x01 \x03(\v2\x1c.nginxui.plugin.v1.ProbeKindR\x05kinds\"\x81\x01\n" +
	"\tProbeKind\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12L\n" +
	"\rconfiguration\x18\x03 \x01(\v2&.nginxui.plugin.v1.ConfigurationSchemaR\rconfiguration\"P\n" +
	"\x0fManifestStorage\x12=\n" +
	"\bbackends\x18\x01 \x03(\v2!.nginxui.plugin.v1.StorageBackendR\bbackends\"\x86\x01\n" +
	"\x0eStorageBackend\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12L\n" +
	"\rconfiguration\x18\x03 \x01(\v2&.nginxui.plugin.v1.ConfigurationSchemaR\rconfiguration\"K\n" +
	"\x0eManifestDeploy\x129\n" +
	"\atargets\x18\x01 \x03(\v2\x1f.nginxui.plugin.v1.DeployTargetR\atargets\"\x84\x01\n" +
	"\fDeployTarget\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12L\n" +
	"\rconfiguration\x18\x03 \x01(\v2&.nginxui.plugin.v1.ConfigurationSchemaR\rconfiguration\"Q\n" +
	"\x11ManifestBlocklist\x12<\n" +
	"\asources\x18\x01 \x03(\v2\".nginxui.plugin.v1.BlocklistSourceR\asources\"\xb0\x01\n" +
	"\x0fBlocklistSource\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12L\n" +
	"\rconfiguration\x18\x03 \x01(\v2&.nginxui.plugin.v1.ConfigurationSchemaR\rconfiguration\x12'\n" +
	"\x0frefresh_seconds\x18\x04 \x01(\x05R\x0erefreshSeconds\"W\n" +
	"\x11ManifestDiscovery\x12B\n" +
	"\tproviders\x18\x01 \x03(\v2$.nginxui.plugin.v1.DiscoveryProviderR\tproviders\"\x89\x01\n" +
	"\x11DiscoveryProvider\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12L\n" +
	"\rconfiguration\x18\x03 \x01(\v2&.nginxui.plugin.v1.ConfigurationSchemaR\rconfiguration\"v\n" +
	"\x0fManifestLogSink\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x05R\tbatchSize\x12*\n" +
	"\x11flush_interval_ms\x18\x02 \x01(\x05R\x0fflushIntervalMs\x12\x18\n" +
	"\aformats\x18\x03 \x03(\tR\aformats\"T\n" +
	"\x13ConfigurationSchema\x12=\n" +
	"\x06fields\x18\x01 \x03(\v2%.nginxui.plugin.v1.ConfigurationFieldR\x06fields\"\xae\x01\n" +
	"\x12ConfigurationField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\thelp_text\x18\x04 \x01(\tR\bhelpText\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\bR\x06secret\"?\n" +
	"\vManifestMCP\x120\n" +
	"\x05tools\x18\x01 \x03(\v2\x1a.nginxui.plugin.v1.MCPToolR\x05tools\"{\n" +
	"\aMCPTool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\finput_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\"~\n" +
	"\x0eSettingsSchema\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x16\n" +
	"\x06footer\x18\x02 \x01(\tR\x06footer\x12<\n" +
	"\bsettings\x18\x03 \x03(\v2 .nginxui.plugin.v1.SettingsFieldR\bsettings\"\x80\x02\n" +
	"\rSettingsField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\thelp_text\x18\x04 \x01(\tR\bhelpText\x120\n" +
	"\adefault\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\adefault\x12;\n" +
	"\aoptions\x18\x06 \x03(\v2!.nginxui.plugin.v1.SettingsOptionR\aoptions\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\"<\n" +
	"\x0eSettingsOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05labelBBZ@github.com/nginxui/plugin-spec/gen/go/nginxui/plugin/v1;pluginv1b\x06proto3"

var (
	file_nginxui_plugin_v1_manifest_proto_rawDescOnce sync.Once
	file_nginxui_plugin_v1_manifest_proto_rawDescData []byte
)

func file_nginxui_plugin_v1_manifest_proto_rawDescGZIP() []byte {
	file_nginxui_plugin_v1_manifest_proto_rawDescOnce.Do(func() {
		file_nginxui_plugin_v1_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_manifest_proto_rawDesc), len(file_nginxui_plugin_v1_manifest_proto_rawDesc)))
	})
	return file_nginxui_plugin_v1_manifest_proto_rawDescData
}

var file_nginxui_plugin_v1_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_nginxui_plugin_v1_manifest_proto_goTypes = []any{
	(*Manifest)(nil),            // 0: nginxui.plugin.v1.Manifest
	(*ManifestI18N)(nil),        // 1: nginxui.plugin.v1.ManifestI18n
	(*ManifestServer)(nil),      // 2: nginxui.plugin.v1.ManifestServer
	(*ManifestResources)(nil),   // 3: nginxui.plugin.v1.ManifestResources
	(*ManifestWebapp)(nil),      // 4: nginxui.plugin.v1.ManifestWebapp
	(*ManifestPage)(nil),        // 5: nginxui.plugin.v1.ManifestPage
	(*ManifestContent)(nil),     // 6: nginxui.plugin.v1.ManifestContent
	(*ManifestRequirement)(nil), // 7: nginxui.plugin.v1.ManifestRequirement
	(*ManifestCron)(nil),        // 8: nginxui.plugin.v1.ManifestCron
	(*ManifestDNS01)(nil),       // 9: nginxui.plugin.v1.ManifestDNS01
	(*DNS01Provider)(nil),       // 10: nginxui.plugin.v1.DNS01Provider
	(*DNS01ProviderLinks)(nil),  // 11: nginxui.plugin.v1.DNS01ProviderLinks
	(*DNS01ProviderForm)(nil),   // 12: nginxui.plugin.v1.DNS01ProviderForm
	(*DNS01ProviderField)(nil),  // 13: nginxui.plugin.v1.DNS01ProviderField
	(*DNS01ProviderMethod)(nil), // 14: nginxui.plugin.v1.DNS01ProviderMethod
	(*ManifestHTTP)(nil),        // 15: nginxui.plugin.v1.ManifestHTTP
	(*ManifestNotify)(nil),      // 16: nginxui.plugin.v1.ManifestNotify
	(*NotifyChannel)(nil),       // 17: nginxui.plugin.v1.NotifyChannel
	(*ManifestProbe)(nil),       // 18: nginxui.plugin.v1.ManifestProbe
	(*ProbeKind)(nil),           // 19: nginxui.plugin.v1.ProbeKind
	(*ManifestStorage)(nil),     // 20: nginxui.plugin.v1.ManifestStorage
	(*StorageBackend)(nil),      // 21: nginxui.plugin.v1.StorageBackend
	(*ManifestDeploy)(nil),      // 22: nginxui.plugin.v1.ManifestDeploy
	(*DeployTarget)(nil),        // 23: nginxui.plugin.v1.DeployTarget
	(*ManifestBlocklist)(nil),   // 24: nginxui.plugin.v1.ManifestBlocklist
	(*BlocklistSource)(nil),     // 25: nginxui.plugin.v1.BlocklistSource
	(*ManifestDiscovery)(nil),   // 26: nginxui.plugin.v1.ManifestDiscovery
	(*DiscoveryProvider)(nil),   // 27: nginxui.plugin.v1.DiscoveryProvider
	(*ManifestLogSink)(nil),     // 28: nginxui.plugin.v1.ManifestLogSink
	(*ConfigurationSchema)(nil), // 29: nginxui.plugin.v1.ConfigurationSchema
	(*ConfigurationField)(nil),  // 30: nginxui.plugin.v1.ConfigurationField
	(*ManifestMCP)(nil),         // 31: nginxui.plugin.v1.ManifestMCP
	(*MCPTool)(nil),             // 32: nginxui.plugin.v1.MCPTool
	(*SettingsSchema)(nil),      // 33: nginxui.plugin.v1.SettingsSchema
	(*SettingsField)(nil),       // 34: nginxui.plugin.v1.SettingsField
	(*SettingsOption)(nil),      // 35: nginxui.plugin.v1.SettingsOption
	nil,                         // 36: nginxui.plugin.v1.Manifest.I18nEntry
	nil,                         // 37: nginxui.plugin.v1.ManifestServer.ExecutablesEntry
	nil,                         // 38: nginxui.plugin.v1.ManifestWebapp.SharedEntry
	nil,                         // 39: nginxui.plugin.v1.ManifestPage.TitleEntry
	nil,                         // 40: nginxui.plugin.v1.DNS01ProviderMethod.ValuesEntry
	(*structpb.Struct)(nil),     // 41: google.protobuf.Struct
	(*structpb.Value)(nil),      // 42: google.protobuf.Value
}
var file_nginxui_plugin_v1_manifest_proto_depIdxs = []int32{
	2,  // 0: nginxui.plugin.v1.Manifest.server:type_name -> nginxui.plugin.v1.ManifestServer
	4,  // 1: nginxui.plugin.v1.Manifest.webapp:type_name -> nginxui.plugin.v1.ManifestWebapp
	6,  // 2: nginxui.plugin.v1.Manifest.content:type_name -> nginxui.plugin.v1.ManifestContent
	7,  // 3: nginxui.plugin.v1.Manifest.requires:type_name -> nginxui.plugin.v1.ManifestRequirement
	8,  // 4: nginxui.plugin.v1.Manifest.cron:type_name -> nginxui.plugin.v1.ManifestCron
	9,  // 5: nginxui.plugin.v1.Manifest.dns01:type_name -> nginxui.plugin.v1.ManifestDNS01
	15, // 6: nginxui.plugin.v1.Manifest.http:type_name -> nginxui.plugin.v1.ManifestHTTP
	33, // 7: nginxui.plugin.v1.Manifest.settings_schema:type_name -> nginxui.plugin.v1.SettingsSchema
	16, // 8: nginxui.plugin.v1.Manifest.notify:type_name -> nginxui.plugin.v1.ManifestNotify
	18, // 9: nginxui.plugin.v1.Manifest.probe:type_name -> nginxui.plugin.v1.ManifestProbe
	31, // 10: nginxui.plugin.v1.Manifest.mcp:type_name -> nginxui.plugin.v1.ManifestMCP
	20, // 11: nginxui.plugin.v1.Manifest.storage:type_name -> nginxui.plugin.v1.ManifestStorage
	22, // 12: nginxui.plugin.v1.Manifest.deploy:type_name -> nginxui.plugin.v1.ManifestDeploy
	24, // 13: nginxui.plugin.v1.Manifest.blocklist:type_name -> nginxui.plugin.v1.ManifestBlocklist
	26, // 14: nginxui.plugin.v1.Manifest.discovery:type_name -> nginxui.plugin.v1.ManifestDiscovery
	28, // 15: nginxui.plugin.v1.Manifest.log_sink:type_name -> nginxui.plugin.v1.ManifestLogSink
	36, // 16: nginxui.plugin.v1.Manifest.i18n:type_name -> nginxui.plugin.v1.Manifest.I18nEntry
	37, // 17: nginxui.plugin.v1.ManifestServer.executables:type_name -> nginxui.plugin.v1.ManifestServer.ExecutablesEntry
	3,  // 18: nginxui.plugin.v1.ManifestServer.resources:type_name -> nginxui.plugin.v1.ManifestResources
	38, // 19: nginxui.plugin.v1.ManifestWebapp.shared:type_name -> nginxui.plugin.v1.ManifestWebapp.SharedEntry
	5,  // 20: nginxui.plugin.v1.ManifestWebapp.pages:type_name -> nginxui.plugin.v1.ManifestPage
	39, // 21: nginxui.plugin.v1.ManifestPage.title:type_name -> nginxui.plugin.v1.ManifestPage.TitleEntry
	10, // 22: nginxui.plugin.v1.ManifestDNS01.providers:type_name -> nginxui.plugin.v1.DNS01Provider
	11, // 23: nginxui.plugin.v1.DNS01Provider.links:type_name -> nginxui.plugin.v1.DNS01ProviderLinks
	12, // 24: nginxui.plugin.v1.DNS01Provider.form:type_name -> nginxui.plugin.v1.DNS01ProviderForm
	13, // 25: nginxui.plugin.v1.DNS01ProviderForm.fields:type_name -> nginxui.plugin.v1.DNS01ProviderField
	14, // 26: nginxui.plugin.v1.DNS01ProviderForm.methods:type_name -> nginxui.plugin.v1.DNS01ProviderMethod
	40, // 27: nginxui.plugin.v1.DNS01ProviderMethod.values:type_name -> nginxui.plugin.v1.DNS01ProviderMethod.ValuesEntry
	17, // 28: nginxui.plugin.v1.ManifestNotify.channels:type_name -> nginxui.plugin.v1.NotifyChannel
	29, // 29: nginxui.plugin.v1.NotifyChannel.configuration:type_name -> nginxui.plugin.v1.ConfigurationSchema
	19, // 30: nginxui.plugin.v1.ManifestProbe.kinds:type_name -> nginxui.plugin.v1.ProbeKind
	29, // 31: nginxui.plugin.v1.ProbeKind.configuration:type_name -> nginxui.plugin.v1.ConfigurationSchema
	21, // 32: nginxui.plugin.v1.ManifestStorage.backends:type_name -> nginxui.plugin.v1.StorageBackend
	29, // 33: nginxui.plugin.v1.StorageBackend.configuration:type_name -> nginxui.plugin.v1.ConfigurationSchema
	23, // 34: nginxui.plugin.v1.ManifestDeploy.targets:type_name -> nginxui.plugin.v1.DeployTarget
	29, // 35: nginxui.plugin.v1.DeployTarget.configuration:type_name -> nginxui.plugin.v1.ConfigurationSchema
	25, // 36: nginxui.plugin.v1.ManifestBlocklist.sources:type_name -> nginxui.plugin.v1.BlocklistSource
	29, // 37: nginxui.plugin.v1.BlocklistSource.configuration:type_name -> nginxui.plugin.v1.ConfigurationSchema
	27, // 38: nginxui.plugin.v1.ManifestDiscovery.providers:type_name -> nginxui.plugin.v1.DiscoveryProvider
	29, // 39: nginxui.plugin.v1.DiscoveryProvider.configuration:type_name -> nginxui.plugin.v1.ConfigurationSchema
	30, // 40: nginxui.plugin.v1.ConfigurationSchema.fields:type_name -> nginxui.plugin.v1.ConfigurationField
	32, // 41: nginxui.plugin.v1.ManifestMCP.tools:type_name -> nginxui.plugin.v1.MCPTool
	41, // 42: nginxui.plugin.v1.MCPTool.input_schema:type_name -> google.protobuf.Struct
	34, // 43: nginxui.plugin.v1.SettingsSchema.settings:type_name -> nginxui.plugin.v1.SettingsField
	42, // 44: nginxui.plugin.v1.SettingsField.default:type_name -> google.protobuf.Value
	35, // 45: nginxui.plugin.v1.SettingsField.options:type_name -> nginxui.plugin.v1.SettingsOption
	1,  // 46: nginxui.plugin.v1.Manifest.I18nEntry.value:type_name -> nginxui.plugin.v1.ManifestI18n
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_nginxui_plugin_v1_manifest_proto_init() }
func file_nginxui_plugin_v1_manifest_proto_init() {
	if File_nginxui_plugin_v1_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_manifest_proto_rawDesc), len(file_nginxui_plugin_v1_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nginxui_plugin_v1_manifest_proto_goTypes,
		DependencyIndexes: file_nginxui_plugin_v1_manifest_proto_depIdxs,
		MessageInfos:      file_nginxui_plugin_v1_manifest_proto_msgTypes,
	}.Build()
	File_nginxui_plugin_v1_manifest_proto = out.File
	file_nginxui_plugin_v1_manifest_proto_goTypes = nil
	file_nginxui_plugin_v1_manifest_proto_depIdxs = nil
}
