// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nginxui/plugin/v1/mcp.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPCallRequest is the params of mcp.call.
type MCPCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name declared in the manifest, without the host prefix.
	Tool string `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	// Arguments the MCP client sent. A JSON object meant to match the tool's
	// input_schema.
	Arguments     *structpb.Struct `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPCallRequest) Reset() {
	*x = MCPCallRequest{}
	mi := &file_nginxui_plugin_v1_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPCallRequest) ProtoMessage() {}

func (x *MCPCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPCallRequest.ProtoReflect.Descriptor instead.
func (*MCPCallRequest) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *MCPCallRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *MCPCallRequest) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// MCPCallResponse is the result of mcp.call.
type MCPCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the tool returns to the MCP client.
	Content []*MCPContent `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	// The tool ran and failed. content explains why.
	IsError       bool `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPCallResponse) Reset() {
	*x = MCPCallResponse{}
	mi := &file_nginxui_plugin_v1_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPCallResponse) ProtoMessage() {}

func (x *MCPCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPCallResponse.ProtoReflect.Descriptor instead.
func (*MCPCallResponse) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *MCPCallResponse) GetContent() []*MCPContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MCPCallResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// MCPContent is one content block of a tool result.
type MCPContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content type. Only "text" is defined.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Text of a "text" block.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPContent) Reset() {
	*x = MCPContent{}
	mi := &file_nginxui_plugin_v1_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPContent) ProtoMessage() {}

func (x *MCPContent) ProtoReflect() protoreflect.Message {
	mi := &file_nginxui_plugin_v1_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPContent.ProtoReflect.Descriptor instead.
func (*MCPContent) Descriptor() ([]byte, []int) {
	return file_nginxui_plugin_v1_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *MCPContent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MCPContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_nginxui_plugin_v1_mcp_proto protoreflect.FileDescriptor

const file_nginxui_plugin_v1_mcp_proto_rawDesc = "" +
	"\n" +
	"\x1bnginxui/plugin/v1/mcp.proto\x12\x11nginxui.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fnginxui/plugin/v1/options.proto\"[\n" +
	"\x0eMCPCallRequest\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x125\n" +
	"\targuments\x18\x02 \x01(\v2\x17.google.protobuf.StructR\targuments\"e\n" +
	"\x0fMCPCallResponse\x127\n" +
	"\acontent\x18\x01 \x03(\v2\x1d.nginxui.plugin.v1.MCPContentR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\"4\n" +
	"\n" +
	"MCPContent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text2b\n" +
	"\x03MCP\x12[\n" +
	"\x04Call\x12!.nginxui.plugin.v1.MCPCallRequest\x1a\".nginxui.plugin.v1.MCPCallResponse\"\f\xaa\xb8\x19\bmcp.callBBZ@github.com/nginxui/plugin-spec/gen/go/nginxui/plugin/v1;pluginv1b\x06proto3"

var (
	file_nginxui_plugin_v1_mcp_proto_rawDescOnce sync.Once
	file_nginxui_plugin_v1_mcp_proto_rawDescData []byte
)

func file_nginxui_plugin_v1_mcp_proto_rawDescGZIP() []byte {
	file_nginxui_plugin_v1_mcp_proto_rawDescOnce.Do(func() {
		file_nginxui_plugin_v1_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_mcp_proto_rawDesc), len(file_nginxui_plugin_v1_mcp_proto_rawDesc)))
	})
	return file_nginxui_plugin_v1_mcp_proto_rawDescData
}

var file_nginxui_plugin_v1_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nginxui_plugin_v1_mcp_proto_goTypes = []any{
	(*MCPCallRequest)(nil),  // 0: nginxui.plugin.v1.MCPCallRequest
	(*MCPCallResponse)(nil), // 1: nginxui.plugin.v1.MCPCallResponse
	(*MCPContent)(nil),      // 2: nginxui.plugin.v1.MCPContent
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_nginxui_plugin_v1_mcp_proto_depIdxs = []int32{
	3, // 0: nginxui.plugin.v1.MCPCallRequest.arguments:type_name -> google.protobuf.Struct
	2, // 1: nginxui.plugin.v1.MCPCallResponse.content:type_name -> nginxui.plugin.v1.MCPContent
	0, // 2: nginxui.plugin.v1.MCP.Call:input_type -> nginxui.plugin.v1.MCPCallRequest
	1, // 3: nginxui.plugin.v1.MCP.Call:output_type -> nginxui.plugin.v1.MCPCallResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nginxui_plugin_v1_mcp_proto_init() }
func file_nginxui_plugin_v1_mcp_proto_init() {
	if File_nginxui_plugin_v1_mcp_proto != nil {
		return
	}
	file_nginxui_plugin_v1_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_mcp_proto_rawDesc), len(file_nginxui_plugin_v1_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nginxui_plugin_v1_mcp_proto_goTypes,
		DependencyIndexes: file_nginxui_plugin_v1_mcp_proto_depIdxs,
		MessageInfos:      file_nginxui_plugin_v1_mcp_proto_msgTypes,
	}.Build()
	File_nginxui_plugin_v1_mcp_proto = out.File
	file_nginxui_plugin_v1_mcp_proto_goTypes = nil
	file_nginxui_plugin_v1_mcp_proto_depIdxs = nil
}
