// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nginxui/plugin/v1/options.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_nginxui_plugin_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         52101,
		Name:          "nginxui.plugin.v1.rpc_name",
		Tag:           "bytes,52101,opt,name=rpc_name",
		Filename:      "nginxui/plugin/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         52102,
		Name:          "nginxui.plugin.v1.notification",
		Tag:           "varint,52102,opt,name=notification",
		Filename:      "nginxui/plugin/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         52103,
		Name:          "nginxui.plugin.v1.streaming",
		Tag:           "varint,52103,opt,name=streaming",
		Filename:      "nginxui/plugin/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// JSON-RPC method name of the rpc on the stdio transport, e.g.
	// "dns01.present". Every rpc of this package MUST set it and the names MUST
	// be unique across the package.
	//
	// optional string rpc_name = 52101;
	E_RpcName = &file_nginxui_plugin_v1_options_proto_extTypes[0]
	// Marks a one-way message. On the stdio transport it is sent as a JSON-RPC
	// notification (no id) and MUST NOT be answered. On gRPC it stays a unary
	// call whose empty response the caller ignores.
	//
	// optional bool notification = 52102;
	E_Notification = &file_nginxui_plugin_v1_options_proto_extTypes[1]
	// Marks a client streaming rpc: the caller sends any number of request
	// messages and the callee answers once, with the response message, after
	// the stream ended. Such an rpc has no JSON-RPC form. It travels on gRPC
	// only and a peer answers -32601 for its rpc_name on stdio
	// (spec/03-wire-protocol.md WIRE-12). The rpc MUST also be declared with
	// a streamed request in the proto.
	//
	// optional bool streaming = 52103;
	E_Streaming = &file_nginxui_plugin_v1_options_proto_extTypes[2]
)

var File_nginxui_plugin_v1_options_proto protoreflect.FileDescriptor

const file_nginxui_plugin_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x1fnginxui/plugin/v1/options.proto\x12\x11nginxui.plugin.v1\x1a google/protobuf/descriptor.proto:;\n" +
	"\brpc_name\x12\x1e.google.protobuf.MethodOptions\x18\x85\x97\x03 \x01(\tR\arpcName:D\n" +
	"\fnotification\x12\x1e.google.protobuf.MethodOptions\x18\x86\x97\x03 \x01(\bR\fnotification:>\n" +
	"\tstreaming\x12\x1e.google.protobuf.MethodOptions\x18\x87\x97\x03 \x01(\bR\tstreamingBBZ@github.com/nginxui/plugin-spec/gen/go/nginxui/plugin/v1;pluginv1b\x06proto3"

var file_nginxui_plugin_v1_options_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_nginxui_plugin_v1_options_proto_depIdxs = []int32{
	0, // 0: nginxui.plugin.v1.rpc_name:extendee -> google.protobuf.MethodOptions
	0, // 1: nginxui.plugin.v1.notification:extendee -> google.protobuf.MethodOptions
	0, // 2: nginxui.plugin.v1.streaming:extendee -> google.protobuf.MethodOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nginxui_plugin_v1_options_proto_init() }
func file_nginxui_plugin_v1_options_proto_init() {
	if File_nginxui_plugin_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nginxui_plugin_v1_options_proto_rawDesc), len(file_nginxui_plugin_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_nginxui_plugin_v1_options_proto_goTypes,
		DependencyIndexes: file_nginxui_plugin_v1_options_proto_depIdxs,
		ExtensionInfos:    file_nginxui_plugin_v1_options_proto_extTypes,
	}.Build()
	File_nginxui_plugin_v1_options_proto = out.File
	file_nginxui_plugin_v1_options_proto_goTypes = nil
	file_nginxui_plugin_v1_options_proto_depIdxs = nil
}
