# Nginx UI Template Start
name = "Redirect"
author = "@0xJacky"
description = { en = "Redirect Config", zh_CN = "重定向配置" }

[variables.status]
type = "select"
name = { en = "Status Code", zh_CN = "状态码" }
value = "301"
mask = { "301" = { en = "301 Moved Permanently", zh_CN = "301 永久移动" }, "302" = { en = "302 Found", zh_CN = "302 临时移动" }, "308" = { en = "308 Permanent Redirect", zh_CN = "308 永久重定向" } }

[variables.target]
type = "string"
name = { en = "Target URL", zh_CN = "目标地址" }
value = "https://example.com"
# Nginx UI Template End

location / {
    return {{ .status }} {{ .target }};
}
