package discovery

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/0xJacky/Nginx-UI/internal/config"
	"github.com/0xJacky/Nginx-UI/internal/plugin"
	"github.com/0xJacky/Nginx-UI/model"
	"github.com/0xJacky/Nginx-UI/query"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/uozi-tech/cosy"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

const testKind = "plugin:test-registry"

// fakeRegistry serves testKind with answers the test controls per service.
type fakeRegistry struct {
	mu       sync.Mutex
	services map[string][]Target
	ttl      int
	err      error
	resolves int
}

func (f *fakeRegistry) Providers() []Provider {
	return []Provider{{Kind: testKind, Name: "Test registry", Fields: []ProviderField{
		{Key: "address", DisplayName: "Address", Required: true},
	}}}
}

func (f *fakeRegistry) Resolve(_ context.Context, _ string, config map[string]string, service string) (Result, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.resolves++
	if f.err != nil {
		return Result{}, f.err
	}
	if config["address"] == "" {
		return Result{}, cosy.WrapErrorWithParams(plugin.ErrDiscoveryConfigInvalid, "address", "it is required")
	}
	targets, ok := f.services[service]
	if !ok {
		return Result{}, cosy.WrapErrorWithParams(plugin.ErrDiscoveryConfigInvalid, "service", "unknown service")
	}
	return Result{Targets: append([]Target(nil), targets...), TTLSeconds: f.ttl}, nil
}

func (f *fakeRegistry) set(service string, targets []Target, ttl int, err error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.services == nil {
		f.services = map[string][]Target{}
	}
	f.services[service] = targets
	f.ttl, f.err = ttl, err
}

var registerRegistry = sync.OnceValue(func() *fakeRegistry {
	registry := &fakeRegistry{}
	RegisterSource(registry)
	return registry
})

// stubNginx stands in for nginx -t and the reload.
type stubNginx struct {
	mu       sync.Mutex
	reloads  int
	failTest bool
}

func (s *stubNginx) writer() config.GeneratedWriter {
	return config.GeneratedWriter{
		Test: func() error {
			s.mu.Lock()
			defer s.mu.Unlock()
			if s.failTest {
				return errors.New(`duplicate upstream "api"`)
			}
			return nil
		},
		Reload: func() error {
			s.mu.Lock()
			defer s.mu.Unlock()
			s.reloads++
			return nil
		},
	}
}

func (s *stubNginx) reloadCount() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.reloads
}

func setupDB(t *testing.T) {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	require.NoError(t, err)
	sqlDB, err := db.DB()
	require.NoError(t, err)
	sqlDB.SetMaxOpenConns(1)
	require.NoError(t, db.AutoMigrate(&model.UpstreamDiscovery{}))
	originalDB := model.UseDB()
	model.Use(db)
	query.SetDefault(db)
	t.Cleanup(func() {
		model.Use(originalDB)
		if originalDB != nil {
			query.SetDefault(originalDB)
		}
	})
}

func testRunner(t *testing.T) (*Runner, *stubNginx, *time.Time, string) {
	t.Helper()
	confDir := t.TempDir()
	stub := &stubNginx{}
	now := time.Date(2026, 9, 23, 8, 0, 0, 0, time.UTC)
	r := NewRunner(t.Context(),
		WithWriter(stub.writer()),
		WithConfDir(func() string { return confDir }),
		WithClock(func() time.Time { return now }),
	)
	return r, stub, &now, confDir
}

func TestRender(t *testing.T) {
	rendered, err := Render("api", []Target{
		{Address: "10.0.2.7", Port: 8080, Weight: 2, Tags: []string{"canary; }"}},
		{Address: "10.0.1.12", Port: 8080},
		{Address: "10.0.1.12", Port: 8080, Weight: 5},
		{Address: "2001:db8::17", Port: 8443},
		{Address: "::ffff:10.0.3.1", Port: 80},
		{Address: "API.Internal.", Port: 9000, Weight: 1000},
		{Address: "web_1", Port: 80},
		{Address: "10.0.0.1", Port: 0},
		{Address: "10.0.0.1", Port: 70000},
		{Address: "10.0.0.1", Port: 80, Weight: 1001},
		{Address: "10.0.0.1", Port: 80, Weight: -1},
		{Address: "10.0.0.1:80", Port: 80},
		{Address: "a b", Port: 80},
		{Address: "evil;server", Port: 80},
		{Address: "fe80::1%eth0", Port: 80},
		{Address: "", Port: 80},
	}, "keepalive 32;\r\n\n  least_conn;")
	require.NoError(t, err)
	assert.Equal(t, strings.Join([]string{
		"# generated by nginx-ui",
		"# Resolved by upstream discovery; changes to this file are overwritten.",
		"upstream api {",
		"    server 10.0.1.12:8080 weight=1;",
		"    server 10.0.2.7:8080 weight=2;",
		"    server 10.0.3.1:80 weight=1;",
		"    server [2001:db8::17]:8443 weight=1;",
		"    server api.internal:9000 weight=1000;",
		"    server web_1:80 weight=1;",
		"    keepalive 32;",
		"    least_conn;",
		"}",
		"",
	}, "\n"), string(rendered.Content))
	assert.Equal(t, 6, rendered.Written)
	assert.Equal(t, 9, rendered.Dropped)
	assert.Equal(t, 1, rendered.Duplicates)

	_, err = Render("api", []Target{{Address: "bad host", Port: 80}}, "")
	assert.ErrorIs(t, err, ErrNoTargets)
	_, err = Render("api", nil, "")
	assert.ErrorIs(t, err, ErrNoTargets)
	_, err = Render("api", []Target{{Address: "10.0.0.1", Port: 80}}, "} server evil:80; {")
	assert.Error(t, err)
	_, err = Render("bad name", []Target{{Address: "10.0.0.1", Port: 80}}, "")
	assert.Error(t, err)
}

func TestValidation(t *testing.T) {
	for _, name := range []string{"api", "api_v2", "backend.eu-1", "_default", "A1"} {
		assert.True(t, IsValidUpstreamName(name), name)
	}
	for _, name := range []string{"", "-api", ".api", "../api", "a/b", "a b", "a;b", "a{b", strings.Repeat("a", 65)} {
		assert.False(t, IsValidUpstreamName(name), name)
	}
	assert.True(t, IsValidExtraDirectives("keepalive 32;\nleast_conn;"))
	assert.False(t, IsValidExtraDirectives("} server x:80; {"))
	assert.Equal(t, "include upstreams/api.conf;", IncludeLine("api"))
}

func TestRunnerWritesTheUpstreamAndReloadsOnlyOnChange(t *testing.T) {
	registry := registerRegistry()
	setupDB(t)
	r, stub, now, confDir := testRunner(t)

	registry.set("api", []Target{{Address: "10.0.1.12", Port: 8080}, {Address: "bad host", Port: 80}}, 0, nil)
	binding := &model.UpstreamDiscovery{
		UpstreamName: "api", Kind: testKind, Config: map[string]string{"address": "https://registry"},
		Service: "api", RefreshSeconds: 60, ExtraDirectives: "keepalive 16;", Enabled: true,
	}
	require.NoError(t, query.UpstreamDiscovery.Create(binding))

	r.RefreshDue()
	path := filepath.Join(confDir, DirName, "api.conf")
	assert.Equal(t, path, r.Path("api"))
	content, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Contains(t, string(content), "upstream api {\n    server 10.0.1.12:8080 weight=1;\n    keepalive 16;\n}\n")
	assert.Equal(t, 1, stub.reloadCount())

	stored, err := query.UpstreamDiscovery.Where(query.UpstreamDiscovery.ID.Eq(binding.ID)).First()
	require.NoError(t, err)
	assert.Equal(t, model.RefreshStatusOK, stored.LastStatus)
	assert.Equal(t, 1, stored.TargetCount)
	assert.Contains(t, stored.LastMessage, "1 invalid targets dropped")
	assert.True(t, stored.NextRunAt.Equal(now.Add(time.Minute)))

	// Due with the same servers: no reload.
	*now = now.Add(2 * time.Minute)
	r.RefreshDue()
	assert.Equal(t, 1, stub.reloadCount())

	// A new server is written and reloaded; a short ttl brings the next run
	// forward, but not below the minimum.
	registry.set("api", []Target{{Address: "10.0.1.12", Port: 8080}, {Address: "10.0.2.7", Port: 8080, Weight: 3}}, 2, nil)
	stored, err = r.Refresh(t.Context(), binding.ID)
	require.NoError(t, err)
	assert.Equal(t, 2, stored.TargetCount)
	assert.Equal(t, 2, stub.reloadCount())
	assert.True(t, stored.NextRunAt.Equal(now.Add(MinRefreshSeconds*time.Second)), "next run %v", stored.NextRunAt)
}

func TestRunnerKeepsTheUpstreamOnFailure(t *testing.T) {
	registry := registerRegistry()
	setupDB(t)
	r, stub, now, _ := testRunner(t)

	registry.set("web", []Target{{Address: "10.0.1.12", Port: 80}}, 0, nil)
	binding := &model.UpstreamDiscovery{
		UpstreamName: "web", Kind: testKind, Config: map[string]string{"address": "https://registry"},
		Service: "web", RefreshSeconds: 3600, Enabled: true,
	}
	require.NoError(t, query.UpstreamDiscovery.Create(binding))
	_, err := r.Refresh(t.Context(), binding.ID)
	require.NoError(t, err)
	before, err := os.ReadFile(r.Path("web"))
	require.NoError(t, err)

	// No server left: the previous upstream stays.
	registry.set("web", []Target{}, 0, nil)
	stored, err := r.Refresh(t.Context(), binding.ID)
	require.NoError(t, err)
	assert.Equal(t, model.RefreshStatusFailed, stored.LastStatus)
	assert.Contains(t, stored.LastMessage, "no valid server")
	assert.Equal(t, 1, stored.TargetCount)
	assert.True(t, stored.NextRunAt.Equal(now.Add(retryAfterFailure)))

	// The provider fails: the previous upstream stays.
	registry.set("web", nil, 0, errors.New("registry is down"))
	stored, err = r.Refresh(t.Context(), binding.ID)
	require.NoError(t, err)
	assert.Contains(t, stored.LastMessage, "registry is down")

	// nginx rejects the upstream: the previous file is put back.
	registry.set("web", []Target{{Address: "10.0.9.9", Port: 80}}, 0, nil)
	stub.failTest = true
	stored, err = r.Refresh(t.Context(), binding.ID)
	require.NoError(t, err)
	assert.Equal(t, model.RefreshStatusFailed, stored.LastStatus)
	assert.Contains(t, stored.LastMessage, "duplicate upstream")

	after, err := os.ReadFile(r.Path("web"))
	require.NoError(t, err)
	assert.Equal(t, string(before), string(after))
	assert.Equal(t, 1, stub.reloadCount())
}

func TestRunnerRemove(t *testing.T) {
	registry := registerRegistry()
	setupDB(t)
	r, stub, _, _ := testRunner(t)

	registry.set("api", []Target{{Address: "10.0.1.12", Port: 8080}}, 0, nil)
	binding := &model.UpstreamDiscovery{
		UpstreamName: "api", Kind: testKind, Config: map[string]string{"address": "a"}, Service: "api", RefreshSeconds: 60, Enabled: true,
	}
	require.NoError(t, query.UpstreamDiscovery.Create(binding))
	_, err := r.Refresh(t.Context(), binding.ID)
	require.NoError(t, err)

	stub.failTest = true
	var cosyErr *cosy.Error
	require.ErrorAs(t, r.Remove("api"), &cosyErr)
	assert.Equal(t, int32(55213), cosyErr.Code)
	assert.FileExists(t, r.Path("api"))

	stub.failTest = false
	require.NoError(t, r.Remove("api"))
	assert.NoFileExists(t, r.Path("api"))
	require.NoError(t, r.Remove("../escape"), "an invalid name never reaches the filesystem")
}

func TestRegistry(t *testing.T) {
	registerRegistry()
	assert.NoError(t, ValidateConfig(testKind, map[string]string{"address": "a"}))
	var cosyErr *cosy.Error
	require.ErrorAs(t, ValidateConfig(testKind, map[string]string{}), &cosyErr)
	assert.Equal(t, int32(55208), cosyErr.Code)
	require.ErrorAs(t, ValidateConfig("plugin:gone", nil), &cosyErr)
	assert.Equal(t, int32(55207), cosyErr.Code)

	found := false
	for _, provider := range Providers() {
		found = found || provider.Kind == testKind
	}
	assert.True(t, found)
}
