package config

import (
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// fakeNginx counts tests and reloads and fails them on demand.
type fakeNginx struct {
	tests, reloads int
	failTest       bool
	failReloads    int
	// seen records the file content every test saw.
	seen []string
	path string
}

func (f *fakeNginx) writer() GeneratedWriter {
	return GeneratedWriter{
		Test: func() error {
			f.tests++
			content, _ := os.ReadFile(f.path)
			f.seen = append(f.seen, string(content))
			if f.failTest {
				return errors.New("unknown directive")
			}
			return nil
		},
		Reload: func() error {
			f.reloads++
			if f.failReloads > 0 {
				f.failReloads--
				return errors.New("reload failed")
			}
			return nil
		},
	}
}

func TestGeneratedWriterReloadsOnlyOnChange(t *testing.T) {
	path := filepath.Join(t.TempDir(), "blocklists", "1.conf")
	nginx := &fakeNginx{path: path}
	writer := nginx.writer()

	changed, err := writer.Apply(path, []byte("# generated by nginx-ui\ndeny 10.0.0.1;\n"))
	require.NoError(t, err)
	assert.True(t, changed)
	assert.Equal(t, 1, nginx.tests)
	assert.Equal(t, 1, nginx.reloads)
	assert.Equal(t, "# generated by nginx-ui\ndeny 10.0.0.1;\n", nginx.seen[0], "the test sees the new file")

	changed, err = writer.Apply(path, []byte("# generated by nginx-ui\ndeny 10.0.0.1;\n"))
	require.NoError(t, err)
	assert.False(t, changed)
	assert.Equal(t, 1, nginx.reloads, "the same content does not reload nginx")

	changed, err = writer.Apply(path, []byte("# generated by nginx-ui\n"))
	require.NoError(t, err)
	assert.True(t, changed)
	assert.Equal(t, 2, nginx.reloads)

	entries, err := os.ReadDir(filepath.Dir(path))
	require.NoError(t, err)
	assert.Len(t, entries, 1, "no temporary file is left behind")
}

func TestGeneratedWriterRestoresTheFileWhenTheTestFails(t *testing.T) {
	path := filepath.Join(t.TempDir(), "1.conf")
	require.NoError(t, os.WriteFile(path, []byte("old\n"), 0o644))
	nginx := &fakeNginx{path: path, failTest: true}

	changed, err := nginx.writer().Apply(path, []byte("new\n"))
	assert.False(t, changed)
	var testErr *TestError
	require.ErrorAs(t, err, &testErr)
	assert.Equal(t, 0, nginx.reloads)
	content, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, "old\n", string(content))

	// A file that did not exist is removed again.
	fresh := filepath.Join(filepath.Dir(path), "2.conf")
	nginx.path = fresh
	_, err = nginx.writer().Apply(fresh, []byte("new\n"))
	require.Error(t, err)
	_, err = os.Stat(fresh)
	assert.True(t, os.IsNotExist(err))
}

func TestGeneratedWriterRestoresTheFileWhenTheReloadFails(t *testing.T) {
	path := filepath.Join(t.TempDir(), "1.conf")
	require.NoError(t, os.WriteFile(path, []byte("old\n"), 0o644))
	nginx := &fakeNginx{path: path, failReloads: 1}

	changed, err := nginx.writer().Apply(path, []byte("new\n"))
	assert.False(t, changed)
	require.Error(t, err)
	var testErr *TestError
	assert.False(t, errors.As(err, &testErr))
	assert.Equal(t, 2, nginx.reloads, "nginx is reloaded again with the previous file")
	content, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, "old\n", string(content))
}

func TestGeneratedWriterRemove(t *testing.T) {
	path := filepath.Join(t.TempDir(), "1.conf")
	nginx := &fakeNginx{path: path}
	writer := nginx.writer()

	removed, err := writer.Remove(path)
	require.NoError(t, err)
	assert.False(t, removed)
	assert.Equal(t, 0, nginx.reloads)

	require.NoError(t, os.WriteFile(path, []byte("deny 10.0.0.1;\n"), 0o644))
	nginx.failTest = true
	_, err = writer.Remove(path)
	var testErr *TestError
	require.ErrorAs(t, err, &testErr, "a file nginx still includes is kept")
	assert.FileExists(t, path)

	nginx.failTest = false
	removed, err = writer.Remove(path)
	require.NoError(t, err)
	assert.True(t, removed)
	assert.NoFileExists(t, path)
	assert.Equal(t, 1, nginx.reloads)
}
