package config

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/0xJacky/Nginx-UI/internal/nginx"
)

// GeneratedHeader is the first line of every file nginx-ui generates for
// nginx, so a person reading the configuration knows not to edit it.
const GeneratedHeader = "# generated by nginx-ui"

// TestError reports that nginx rejected the configuration with a generated
// file in place. The previous file was put back and nginx was not reloaded.
type TestError struct {
	Err error
}

func (e *TestError) Error() string { return "nginx configuration test failed: " + e.Err.Error() }

func (e *TestError) Unwrap() error { return e.Err }

// GeneratedWriter writes the files nginx-ui generates into the nginx
// configuration directory, such as blocklists and discovered upstreams, and
// reloads nginx only when a file changed. The zero value uses the nginx
// control of the host.
type GeneratedWriter struct {
	// Test checks the whole configuration, nginx -t by default.
	Test func() error
	// Reload makes nginx load the configuration.
	Reload func() error
}

func (w GeneratedWriter) test() error {
	if w.Test != nil {
		return w.Test()
	}
	if result := nginx.Control(nginx.TestConfig); result.IsError() {
		return result.GetError()
	}
	return nil
}

func (w GeneratedWriter) reload() error {
	if w.Reload != nil {
		return w.Reload()
	}
	if result := nginx.Control(nginx.Reload); result.IsError() {
		return result.GetError()
	}
	return nil
}

// Apply replaces path with content when the two differ, then tests the
// configuration and reloads nginx. changed reports whether nginx now serves
// the new content. When the test or the reload fails the previous file is
// put back; a failed test is a *TestError.
func (w GeneratedWriter) Apply(path string, content []byte) (changed bool, err error) {
	release := LockApply()
	defer release()

	current, err := nginx.ReadFile(path)
	switch {
	case err == nil && bytes.Equal(current, content):
		return false, nil
	case err != nil && !os.IsNotExist(err):
		return false, err
	}

	snapshot, err := CaptureFile(path)
	if err != nil {
		return false, err
	}
	if err = nginx.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err = replaceAtomically(path, content); err != nil {
		return false, err
	}
	if err = w.testAndReload(path, snapshot); err != nil {
		return false, err
	}
	return true, nil
}

// Remove deletes a generated file, then tests the configuration and reloads
// nginx. removed is false when there was no file. A configuration that still
// includes the file fails the test: the file is put back and the error is a
// *TestError.
func (w GeneratedWriter) Remove(path string) (removed bool, err error) {
	release := LockApply()
	defer release()

	exists, err := nginx.Exists(path)
	if err != nil || !exists {
		return false, err
	}
	snapshot, err := CaptureFile(path)
	if err != nil {
		return false, err
	}
	if err = nginx.Remove(path); err != nil {
		return false, err
	}
	if err = w.testAndReload(path, snapshot); err != nil {
		return false, err
	}
	return true, nil
}

// testAndReload validates the configuration with the new state of path and
// reloads nginx, putting the snapshot back when either step fails.
func (w GeneratedWriter) testAndReload(path string, snapshot FileSnapshot) error {
	if err := w.test(); err != nil {
		return RollbackError(&TestError{Err: err}, func() error { return snapshot.Restore(path) })
	}
	if err := w.reload(); err != nil {
		return RollbackError(fmt.Errorf("reload nginx: %w", err), func() error {
			if err := snapshot.Restore(path); err != nil {
				return err
			}
			// Bring the running nginx back to what it served before.
			if err := w.test(); err != nil {
				return err
			}
			return w.reload()
		})
	}
	return nil
}

// replaceAtomically writes content to a temporary file next to path and
// moves it over path, so nginx never reads a half written file.
func replaceAtomically(path string, content []byte) error {
	var random [8]byte
	if _, err := rand.Read(random[:]); err != nil {
		return err
	}
	tmpPath := filepath.Join(filepath.Dir(path), "."+filepath.Base(path)+"."+hex.EncodeToString(random[:])+".tmp")

	file, err := nginx.OpenFile(tmpPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	_, writeErr := file.Write(content)
	closeErr := file.Close()
	if err = errors.Join(writeErr, closeErr); err != nil {
		_ = nginx.Remove(tmpPath)
		return err
	}
	if err = nginx.Chmod(tmpPath, 0o644); err != nil {
		_ = nginx.Remove(tmpPath)
		return err
	}

	if err = nginx.Rename(tmpPath, path); err == nil {
		return nil
	}
	// SFTP servers commonly refuse to rename onto an existing file.
	if err = nginx.Remove(path); err != nil && !os.IsNotExist(err) {
		_ = nginx.Remove(tmpPath)
		return err
	}
	if err = nginx.Rename(tmpPath, path); err != nil {
		_ = nginx.Remove(tmpPath)
		return err
	}
	return nil
}
