apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ui.fullname" . }}
  labels:
    {{- include "nginx-ui.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "nginx-ui.selectorLabels" . | nindent 4 }}
