apiVersion: v2
name: nginx-ui
description: A web interface for managing Nginx configurations
type: application
version: 2.5.2
appVersion: "2.5.2"
kubeVersion: ">=1.25.0-0"
home: https://nginxui.com
icon: https://nginxui.com/logo.png
sources:
  - https://github.com/0xJacky/nginx-ui
maintainers:
  - name: Nginx UI maintainers
    url: https://github.com/0xJacky/nginx-ui
keywords:
  - nginx
  - proxy
  - web-ui
annotations:
  artifacthub.io/category: networking
