name: Merge Branches

on:
  pull_request:
    branches:
      - 'dev'
    types: [ closed ]
  release:
    types:
      - published

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.action == 'published'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
            ref: 'main'
            fetch-depth: 0

      - name: Merge dev to main branch
        run: |
          git merge --ff-only -- origin/dev
          git push
